Repository decentraland/explorer, pull requests merged in 2020-10, with the labels that each got.

#1377 fix: Voice Chat Echo Cancellation workaround
  kernel/package-lock.json
  kernel/package.json
  kernel/packages/shared/comms/actions.ts
  kernel/packages/shared/comms/index.ts
  kernel/packages/shared/comms/reducer.ts
  kernel/packages/shared/comms/sagas.ts
  kernel/packages/unity-interface/BrowserInterface.ts
  kernel/packages/voice-chat-codec/VoiceCommunicator.ts
  kernel/packages/voice-chat-codec/constants.ts
  kernel/static/index.html
  unity-client/Assets/Prefabs/Player.prefab
  unity-client/Assets/Resources/Prefabs/InputController.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/InputController/InputController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/InputController/Resources/ToggleVoiceChatRecording.asset
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/InputController/Resources/ToggleVoiceChatRecording.asset.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/VoiceChat/DCLVoiceChatController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
Labels: ready for review

#1373 fix: Animation plays on awake with an Animator presented
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Animator/DCLAnimator.cs
Labels: ready for review

#1378 fix: remove entity now clears lossy messages to be processed
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MessagingBus.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/PerformanceTests/MessagingBusTest.cs
Labels: ready for review

#1357 fix: scenes audio outside limits
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Audio/DCLAudioSource.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Audio/Tests/AudioTests.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Audio/Tests/AudioTests.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Video/DCLVideoTexture.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Video/Tests/VideoTests.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Video/Tests/VideoTests.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsHUD/Test/SettingsHUDControllerShould.cs
  unity-client/Assets/Scripts/Tests/TestHelpers.cs
Labels: ready for review

#1365 fix: asset bundle texture issues
  unity-client/Assets/ABConverter/Client.cs
  unity-client/Assets/ABConverter/Core.cs
  unity-client/Assets/ABConverter/Tests/ABConverterCoreShould.cs
  unity-client/Assets/ABConverter/Utils.cs
  unity-client/Assets/ABConverter/Wrappers/Implementations/Default/AssetDatabase.cs
  unity-client/Assets/ABConverter/Wrappers/Implementations/Mock/AssetDatabase.cs
  unity-client/Assets/ABConverter/Wrappers/Interfaces/IAssetDatabase.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/TestScene/APK_AB_InteractiveTest.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/TestScene/APK_AB_InteractiveTest.unity
  unity-client/Assets/UnityGLTF/Scripts/Editor/GLTFImporter.cs
  unity-client/Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs
  unity-client/Assets/UnityGLTF/Scripts/Loader/FileLoader.cs
  unity-client/TestResources/GLTF/SimpleCube/SimpleCubeWithSharedNormal.bin
  unity-client/TestResources/GLTF/SimpleCube/SimpleCubeWithSharedNormal.gltf
  unity-client/TestResources/GLTF/SimpleCube/Test.png
Labels: ready for review

#1380 fix: AvatarShape calling OnPoolGet at start + update event + builder handling update event
  unity-client/Assets/Builder/Scripts/Builder.asmdef
  unity-client/Assets/Builder/Scripts/DCLBuilderEntity.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.cs
Labels: ready for review

#1173 fix: early rendering activation
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Rendering/RenderingController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/SceneController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Helpers/Utils/Promise.cs.meta
Labels: merge me!, ready for review

#1383 chore: added DCL NSubstitute package + PrivateChat Implementation
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/ChatController/ChatMessage/ChatMessage.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/Tests/PrivateChatWindowHUDShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/Tests/PrivateChatWindowHUDTests.asmdef
  unity-client/Packages/manifest.json
Labels: merge me!

#1393 feat: add types for ParcelIdentity
  kernel/packages/decentraland-ecs/types/@decentraland/ParcelIdentity/index.d.ts
  kernel/packages/decentraland-ecs/types/tsconfig.json
Labels: ready for review

#1367 chore: WearableController/FacialFeatureController test suite
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarRenderer.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/BodyShapeController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/FacialFeatureController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/Tests/AvatarShapeTests.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/Tests/FacialFeatureControllerShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/Tests/FacialFeatureControllerShould.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/Tests/WearableControllerShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/Tests/WearableControllerShould.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/Tests/WearableItemsShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/WearableController.cs
  unity-client/Assets/Scripts/Tests/TestsBase.cs
  unity-client/TestResources/Avatar/Assets/F_Eyes_01.png
  unity-client/TestResources/Avatar/Assets/F_Eyes_01_Mask.png
Labels: ready for review

#1394 feat: world render profiles
  kernel/packages/config/index.ts
  kernel/packages/entryPoints/unity.ts
  kernel/packages/shared/meta/types.ts
  kernel/packages/shared/types.ts
  kernel/packages/unity-interface/UnityInterface.ts
  unity-client/Assets/Rendering/Profiles/RenderProfileAvatar.cs
  unity-client/Assets/Rendering/Profiles/RenderProfileManifest.cs
  unity-client/Assets/Rendering/Profiles/RenderProfileManifest.cs.meta
  unity-client/Assets/Rendering/Profiles/RenderProfileWorld.cs
  unity-client/Assets/Rendering/Profiles/RenderProfileWorld.cs.meta
  unity-client/Assets/Rendering/Profiles/RenderProfiles.cs
  unity-client/Assets/Rendering/Profiles/Resources/Default Avatar.asset
  unity-client/Assets/Rendering/Profiles/Resources/Default Avatar.asset.meta
  unity-client/Assets/Rendering/Profiles/Resources/Default World.asset
  unity-client/Assets/Rendering/Profiles/Resources/Default World.asset.meta
  unity-client/Assets/Rendering/Profiles/Resources/Halloween Avatar.asset
  unity-client/Assets/Rendering/Profiles/Resources/Halloween Avatar.asset.meta
  unity-client/Assets/Rendering/Profiles/Resources/Halloween World.asset
  unity-client/Assets/Rendering/Profiles/Resources/Halloween World.asset.meta
  unity-client/Assets/Rendering/Profiles/Resources/Render Profile Manifest.asset
  unity-client/Assets/Rendering/Profiles/Resources/Render Profile Manifest.asset.meta
  unity-client/Assets/Rendering/Shaders/Toon/Compiled/ToonShaderCompiled.shader
  unity-client/Assets/Rendering/Shaders/Toon/Master_ToonShader.shadergraph
  unity-client/Assets/Rendering/Utils/ShaderUtils.cs
  unity-client/Assets/Resources/Prefabs/SceneController.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/RenderProfileBridge.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/RenderProfileBridge/RenderProfileBridge.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/RenderProfileBridge/RenderProfileBridge.asmdef.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/RenderProfileBridge/RenderProfileBridge.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/RenderProfileBridge/RenderProfileBridge.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/SceneController.cs
  unity-client/Assets/Scripts/MainScripts/Debugging/WSS/WSSController.asmdef
  unity-client/Assets/Scripts/MainScripts/Debugging/WSS/WSSController.cs
Labels: ready for review

#1403 hotfix: fix type errors in generated ECS definitions
  kernel/scripts/buildEcsTypes.ts
Labels: merge me!

#1406 fix: TextShape now implements visible and opacity correctly
  kernel/packages/decentraland-ecs/src/decentraland/Components.ts
  unity-client/Assets/Scripts/MainScripts/DCL/Components/TextShape/Tests/TextShapeTests.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/TextShape/TextShape.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/UI/UIText/Tests/UITextTests.cs
Labels: ready for review

#1402 fix: rendering activation on teleport
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/SceneController.cs
Labels: ready for review

#1405 feat: uv multichannel support
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/Tests/GLTFImporterTests.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/Tests/GLTFImporterVisualTests.cs
  unity-client/Assets/Shaders/MaterialTransition/LWRP/Lit.shader
  unity-client/Assets/Shaders/MaterialTransition/LWRP/LitForwardPass.hlsl
  unity-client/Assets/Shaders/MaterialTransition/LWRP/LitInput.hlsl
  unity-client/Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs
  unity-client/Assets/UnityGLTF/Scripts/UniformMaps/MetalRough2StandardMap.cs
  unity-client/Assets/UnityGLTF/Scripts/UniformMaps/MetalRoughMap.cs
  unity-client/Assets/UnityGLTF/Scripts/UniformMaps/SpecGloss2StandardMap.cs
  unity-client/Assets/UnityGLTF/Scripts/UniformMaps/SpecGlossMap.cs
  unity-client/Assets/UnityGLTF/Scripts/UniformMaps/StandardMap.cs
  unity-client/TestResources/GLB/PlaneUVsMultichannel/PlaneUVsMultichannel.glb
  unity-client/TestResources/VisualTests/BaselineImages/GLTFImporterVisualTests_ProcessTexturesUVs_0.png
Labels: ready for review

#1410 fix: increase avatar editor scrolling speed
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/AvatarEditorHUD.prefab
Labels: ready for review

#1395 feat: halloween empty parcels
  kernel/packages/decentraland-loader/lifecycle/controllers/EmptyParcelController.ts
  kernel/packages/decentraland-loader/lifecycle/controllers/download.ts
  kernel/packages/decentraland-loader/lifecycle/manager.ts
  kernel/packages/decentraland-loader/lifecycle/worker.ts
  kernel/packages/entryPoints/unity.ts
  kernel/packages/shared/meta/sagas.ts
  kernel/packages/shared/meta/types.ts
  kernel/packages/unity-interface/UnityInterface.ts
  kernel/static/loader/empty-scenes-halloween/contents/EP_01.js
  kernel/static/loader/empty-scenes-halloween/contents/EP_02.js
  kernel/static/loader/empty-scenes-halloween/contents/EP_03.js
  kernel/static/loader/empty-scenes-halloween/contents/EP_04.js
  kernel/static/loader/empty-scenes-halloween/contents/EP_05.js
  kernel/static/loader/empty-scenes-halloween/contents/EP_06.js
  kernel/static/loader/empty-scenes-halloween/contents/EP_07.js
  kernel/static/loader/empty-scenes-halloween/contents/EP_08.js
  kernel/static/loader/empty-scenes-halloween/contents/EP_09.js
  kernel/static/loader/empty-scenes-halloween/contents/EP_10.js
  kernel/static/loader/empty-scenes-halloween/contents/EP_11.js
  kernel/static/loader/empty-scenes-halloween/contents/EP_12.js
  kernel/static/loader/empty-scenes-halloween/contents/QmHalloween01
  kernel/static/loader/empty-scenes-halloween/contents/QmHalloween02
  kernel/static/loader/empty-scenes-halloween/contents/QmHalloween03
  kernel/static/loader/empty-scenes-halloween/contents/QmHalloween04
  kernel/static/loader/empty-scenes-halloween/contents/QmHalloween05
  kernel/static/loader/empty-scenes-halloween/contents/QmHalloween06
  kernel/static/loader/empty-scenes-halloween/contents/QmHalloween07
  kernel/static/loader/empty-scenes-halloween/contents/QmHalloween08
  kernel/static/loader/empty-scenes-halloween/contents/QmHalloween09
  kernel/static/loader/empty-scenes-halloween/contents/QmHalloween10
  kernel/static/loader/empty-scenes-halloween/contents/QmHalloween11
  kernel/static/loader/empty-scenes-halloween/contents/QmHalloween12
  kernel/static/loader/empty-scenes-halloween/contents/QmHalloweenEmptyParcels
  kernel/static/loader/empty-scenes-halloween/contents/QmHalloweenEmptyParcelsEmissive
  kernel/static/loader/empty-scenes-halloween/contents/QmSyvWnb5nKCaGHw9oHLSkwywvS5NYpj6vgb8L121kWveS
  kernel/static/loader/empty-scenes-halloween/contents/QmT1WfQPMBVhgwyxV5SfcfWivZ6hqMCT74nxdKXwyZBiXb
  kernel/static/loader/empty-scenes-halloween/index.json
  unity-client/Assets/Rendering/Profiles/RenderProfileAvatar.cs
  unity-client/Assets/Rendering/Profiles/RenderProfileManifest.cs
  unity-client/Assets/Rendering/Profiles/RenderProfileWorld.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/RenderProfileBridge/RenderProfileBridge.cs
  unity-client/Assets/Scripts/MainScripts/Debugging/WSS/WSSController.cs
Labels: ready for review

#1417 fix: hover popup is not based on raycast distance
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/PointerEventsController.cs
Labels: ready for review

#1426 fix: render profile quality of life issues
  unity-client/Assets/Rendering/Profiles/RenderProfileWorld.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/SceneController.cs
Labels: ready for review

#1404 feat: remote debugger
  kernel/Makefile
  kernel/packages/config/index.ts
  kernel/packages/decentraland-ecs/types/tsconfig.json
  kernel/packages/entryPoints/preview.ts
  kernel/packages/scene-system/cli.scene.system.ts
  kernel/packages/scene-system/scene.system.ts
  kernel/packages/scene-system/sdk/SceneRuntime.ts
  kernel/packages/shared/types.ts
  kernel/packages/shared/world/SceneWorker.ts
  kernel/packages/unity-interface/dcl.ts
Labels: ready for review

#1435 chore: change discord link
  kernel/static/export.html
  kernel/static/index.html
  kernel/static/preview.html
Labels: ready for review

#1420 chore: now AudioSource gets disabled when out of Scene Bounds
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Audio/DCLAudioSource.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Audio/DCLAudioStream.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/ParcelScene.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/SceneBoundariesController/SceneBoundariesChecker.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/SceneBoundariesController/Tests/SceneBoundariesCheckerTests.cs
Labels: ready for review

#1427 fix: "missing camera listener" log spam
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Camera/CameraController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Camera/CameraStateBase.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Camera/CameraStateFPS.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Camera/CameraStateTPS.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Camera/Resources/CameraController.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Camera/Tests/CameraTests.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Helpers/Utils/Promise.cs.meta
Labels: ready for review

#1436 feat: (builder) add config
  kernel/packages/entryPoints/editor.ts
  kernel/packages/shared/types.ts
  kernel/packages/unity-interface/UnityInterface.ts
  unity-client/Assets/Builder/Scripts/DCLBuilderBridge.cs
  unity-client/Assets/Builder/Scripts/DCLBuilderCamera.cs
  unity-client/Assets/Builder/Scripts/DCLBuilderConfig.cs
  unity-client/Assets/Builder/Scripts/DCLBuilderConfig.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/Debug.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/Debug/SceneDebugPlane.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/Debug/SceneDebugPlane.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/ParcelScene.cs
  unity-client/Assets/Scripts/MainScripts/Debugging/WSS/WSSController.cs
Labels: ready for review

#1442 fix: AvatarModel's Equals method
  unity-client/Assets/Scripts/MainScripts/DCL/Models/AvatarModel/AvatarModel.cs
Labels: ready for review

#1397 fix: sdk move player avatars lerping
  README.md
  kernel/package-lock.json
  kernel/packages/shared/apis/RestrictedActionModule.ts
  kernel/packages/shared/comms/index.ts
  kernel/packages/shared/comms/interface/types.ts
  kernel/packages/shared/comms/interface/utils.ts
  kernel/packages/shared/comms/v1/brokerWorldInstanceConnection.ts
  kernel/packages/shared/comms/v1/proto/comms.proto
  kernel/packages/shared/comms/v2/LighthouseWorldInstanceConnection.ts
  kernel/packages/shared/comms/v2/proto/comms.proto
  kernel/packages/shared/comms/v2/proto/comms_pb.d.ts
  kernel/packages/shared/comms/v2/proto/comms_pb.js
  kernel/packages/shared/proto/engineinterface.proto
  kernel/packages/shared/proto/engineinterface_pb.d.ts
  kernel/packages/shared/world/positionThings.ts
  kernel/packages/ui/avatar/avatarSystem.ts
  kernel/packages/unity-interface/BrowserInterface.ts
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/Tests/AvatarShapeTests.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/Tests/AvatarShapeTests.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/DCLCharacterController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MessageDecoder.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Models/Protocol/Engineinterface.cs
  unity-client/Assets/Scripts/Tests/TestHelpers.cs
Labels: ready for review

#1449 Fix typo in Tutorial
  unity-client/Assets/Tutorial/Prefabs/Steps/TutorialStep_TaskbarTooltip_ExploreButton.prefab
Labels: ready for review

#1452 fix: (builder) disable ground's renderers instead of gameobject
  unity-client/Assets/Builder/Scripts/DCLBuilderEnvironment.cs
Labels: ready for review

#1451 fix: scene boundaries checker nullref
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/SceneBoundariesController/SceneBoundariesChecker.cs
Labels: merge me!, ready for review

#1456 feat: configurable MOTD
  kernel/packages/shared/meta/types.ts
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/AssemblyInfo.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/Resources/WelcomeHUD.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/Resources/WelcomeHUDButton.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/Resources/WelcomeHUDButton.prefab.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/Resources/WelcomeNoWalletHUD.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/Tests/WelcomeHUDShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/Tests/WelcomeHUDTests.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/WelcomeHUD.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/WelcomeHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/WelcomeHUDView.cs
Labels: ready for review

#1460 Temporarily turn off the MANA HUD
  kernel/packages/entryPoints/unity.ts
Labels: ready for review

#1462 fix: Don't send all avatar events
  kernel/packages/shared/analytics.ts
  kernel/packages/shared/comms/interface/types.ts
  kernel/packages/ui/avatar/avatarSystem.ts
Labels: ready for review

#1458 feat: add mask for tinting mouths in Avatar
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AssemblyInfo.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarUtils.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/BodyShapeController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/FacialFeatureController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/Shaders/UnlitCutoutTinted.shader
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/Tests/FacialFeatureControllerShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/Tests/VisualTests/AvatarShapeVisualTests.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/Tests/VisualTests/FacialFeatureController_VisualTests.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/Tests/VisualTests/FacialFeatureController_VisualTests.cs.meta
  unity-client/TestResources/Avatar/Assets/dracula_mouth.png
  unity-client/TestResources/Avatar/Assets/dracula_mouth_mask.png
  unity-client/TestResources/Avatar/TestAvatar_MaskMouth.json
  unity-client/TestResources/Avatar/TestCatalog.json
Labels: ready for review

#1450 chore: update canvas mask bottom limit
  unity-client/Assets/Scripts/MainScripts/DCL/Components/UI/UIContainer/UISizeFitter.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/UI/UIScreenSpace/Tests/UIScreenSpaceTests.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/UI/UIScreenSpace/UIScreenSpace.cs
  unity-client/TestResources/VisualTests/BaselineImages/UIContainerStackTest_0.png
Labels: ready for review

#1461 fix: nullcheck in avatar
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/BodyShapeController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/WearableController.cs
Labels: ready for review

#1463 fix: added nullsafe checks in misc files
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Billboard/Billboard.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB/AssetBundlesLoader.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB/AssetPromise_AB.cs
Labels: ready for review

#1466 chore: Halloween Pattern UI atlas updated
  .circleci/config.yml
  unity-client/Assets/Textures/UI/BackgroundPattern.png
  unity-client/Assets/Textures/UI/PatternPC.png
  unity-client/Assets/Textures/UI/TexturesUI.spriteatlas
  unity-client/Assets/Tutorial/Atlas/TutorialStepsAtlas.spriteatlas
Labels: ready for review

#1472 fix: Added nullsafe check in TaskbarHUD -> ShowTutorialOption()
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/TaskbarHUDController.cs
Labels: ready for review

#1471 chore: close HUDs with ESC key
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/EmailPromptHUD/EmailPromptHUD.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/EmailPromptHUD/EmailPromptHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/EmailPromptHUD/Resources/EmailPromptHUD.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/ExploreHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/ExploreHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Resources/ExploreHUD.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HelpAndSupportHUD/HelpAndSupportHUD.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HelpAndSupportHUD/HelpAndSupportHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HelpAndSupportHUD/Resources/HelpAndSupportHUD.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ProfileHUD.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ProfileHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Resources/ProfileHUD.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsHUD/Resources/SettingsHUD.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsHUD/SettingsHUD.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsHUD/SettingsHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsHUD/SettingsHUDView.cs
Labels: ready for review

#1477 fix: (builder) configure camera's default zoom
  kernel/packages/shared/types.ts
  unity-client/Assets/Builder/Scripts/DCLBuilderCamera.cs
  unity-client/Assets/Builder/Scripts/DCLBuilderConfig.cs
Labels: ready for review

#1474 fix: billboard now looks to the camera even in 3rd person mode
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Billboard/Billboard.cs
Labels: ready for review

#1484 chore: removed debug from broken test
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/Tests/VisualTests/FacialFeatureController_VisualTests.cs
Labels: merge me!

#1490 fix: use mainfile in avatar's facial features
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/FacialFeatureController.cs
Labels: ready for review

#1488 fix: ui container rect borders and canvas
  unity-client/Assets/Scripts/MainScripts/DCL/Components/UI/UIContainer/Resources/UIContainerRect.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Components/UI/UIContainer/UISizeFitter.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/UI/UIScreenSpace/UIScreenSpace.cs
  unity-client/TestResources/VisualTests/BaselineImages/UIContainerRectTest_0.png
  unity-client/TestResources/VisualTests/BaselineImages/UIContainerStackTest_0.png
  unity-client/TestResources/VisualTests/BaselineImages/UIImageTest_0.png
  unity-client/TestResources/VisualTests/BaselineImages/UIInputTextTest_0.png
  unity-client/TestResources/VisualTests/BaselineImages/UIScrollRectTest_0.png
Labels: bug, ready for review

#1491 fix: Update segment events for Tutorial
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/GoToGenesisPlazaHUD/GoToGenesisPlazaHUDController.cs
  unity-client/Assets/Tutorial/Prefabs/Resources/TutorialController.prefab
  unity-client/Assets/Tutorial/Scripts/TutorialController.cs
Labels: ready for review

#1492 fix: Unity tests take too long
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/AvatarEditorHUD.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/ItemToggle.cs
Labels: ready for review

#1502 feat: store commit hash to measure performance regressions
  kernel/packages/shared/analytics.ts
  kernel/static/index.html
Labels: merge me!

#1503 fix: ABConverter texture import issue
  unity-client/Assets/Scripts/MainScripts/DCL/Helpers/Utils/ContentServerUtils.cs
  unity-client/Assets/UnityGLTF/Scripts/Editor/GLTFImporter.cs
Labels: ready for review

#1504 chore: add basic support for empty parcels dump to ABConverter
  kernel/static/loader/empty-scenes-halloween/index.json
  unity-client/Assets/ABConverter/AssetBundleMenuItems.cs
Labels: ready for review

#1506 feat: "deep link" tutorial flow marks the tutorial as completed
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Resources/Taskbar.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/TaskbarMoreMenu.cs
  unity-client/Assets/Tutorial/Prefabs/Steps/TutorialStep_TaskbarTooltip_GoToGenesisButton.prefab
  unity-client/Assets/Tutorial/Scripts/Steps/TutorialStep_Tooltip_GoToGenesisButton.cs
  unity-client/Assets/Tutorial/Scripts/TutorialController.cs
  unity-client/Assets/Tutorial/Tests/TutorialControllerShould.cs
Labels: ready for review

#1493 feat: MOTD endpoint
  kernel/packages/entryPoints/unity.ts
  kernel/packages/shared/meta/actions.ts
  kernel/packages/shared/meta/index.ts
  kernel/packages/shared/meta/reducer.ts
  kernel/packages/shared/meta/sagas.ts
  kernel/packages/shared/meta/types.ts
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/Resources/WelcomeHUD.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/WelcomeHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/WelcomeHUDView.cs
  unity-client/Assets/Textures/UI/MOTDHeader.png
  unity-client/Assets/Textures/UI/MOTDHeader.png.meta
  unity-client/Assets/Textures/UI/TexturesUI.spriteatlas
Labels: ready for review

#1509 chore: removing await for MOTD
  kernel/packages/entryPoints/unity.ts
  kernel/packages/shared/meta/index.ts
  kernel/packages/shared/meta/sagas.ts
  kernel/packages/shared/meta/selectors.ts
  kernel/packages/shared/session/sagas.ts
  kernel/packages/shared/session/selectors.ts
Labels: ready for review

#1511 fix: Make the MOTD wait for tutorial finalization
  kernel/packages/entryPoints/unity.ts
  unity-client/Assets/Resources/ScriptableObjects/EmailPromptActive.asset
  unity-client/Assets/Resources/ScriptableObjects/EmailPromptActive.asset.meta
  unity-client/Assets/Resources/ScriptableObjects/MOTDActive.asset
  unity-client/Assets/Resources/ScriptableObjects/MOTDActive.asset.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/EmailPromptHUD/EmailPromptHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/Tests/WelcomeHUDShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/WelcomeHUD.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/WelcomeHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/WelcomeHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/ScriptableObject/CommonScriptableObjects.cs
Labels: ready for review

#1512 release: 2020-10-27
  kernel/packages/entryPoints/unity.ts
  kernel/packages/shared/meta/index.ts
  kernel/packages/shared/meta/sagas.ts
  kernel/packages/shared/meta/selectors.ts
  kernel/packages/shared/session/sagas.ts
  kernel/packages/shared/session/selectors.ts
  unity-client/Assets/Resources/ScriptableObjects/EmailPromptActive.asset
  unity-client/Assets/Resources/ScriptableObjects/EmailPromptActive.asset.meta
  unity-client/Assets/Resources/ScriptableObjects/MOTDActive.asset
  unity-client/Assets/Resources/ScriptableObjects/MOTDActive.asset.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/EmailPromptHUD/EmailPromptHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/Tests/WelcomeHUDShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/WelcomeHUD.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/WelcomeHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/WelcomeHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/ScriptableObject/CommonScriptableObjects.cs
Labels: ready for review

#1516 chore: replace Sprite with Texture2D in avatar snapshot
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/CharacterPreviewController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Tests/AvatarEditorHUDControllerShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Prefabs/ExploreFriendHead.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Scripts/Friends/ExploreFriendsView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExpressionsHUD/ExpressionsHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExpressionsHUD/Resources/ExpressionsHUD.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Resources/FriendEntry.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Resources/FriendRequestEntry.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/Entries/FriendEntryBase.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Tests/FriendEntryShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Tests/FriendRequestEntryShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/PlayerInfoCardHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/Resources/PlayerInfoCardHUD.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/PrivateChatWindowHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/Resources/PrivateChatWindow.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ProfileHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Resources/ProfileHUD.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/ChatHeadButton.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Resources/ChatHead.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfile.cs
  unity-client/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
Labels: ready for review

#1518 chore: remove _ from all ShaderUtils fields
  unity-client/Assets/Rendering/Profiles/RenderProfileAvatar.cs
  unity-client/Assets/Rendering/Utils/ShaderUtils.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarUtils.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Materials/PBRMaterial.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/BlockerController/BlockerAnimationHandler.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Helpers/MaterialHelpers/SRPBatchingHelper/SRPBatchingHelper.cs
Labels: ready for review

#1514 fix: Remove Alice icon from the taskbar during Tutorial
  kernel/packages/shared/types.ts
  kernel/packages/unity-interface/UnityInterface.ts
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/GoToGenesisPlazaHUD.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/GoToGenesisPlazaHUD/GoToGenesisPlazaHUD.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/GoToGenesisPlazaHUD/GoToGenesisPlazaHUD.asmdef.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/GoToGenesisPlazaHUD/GoToGenesisPlazaHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/GoToGenesisPlazaHUD/GoToGenesisPlazaHUDController.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/GoToGenesisPlazaHUD/GoToGenesisPlazaHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/GoToGenesisPlazaHUD/GoToGenesisPlazaHUDView.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/GoToGenesisPlazaHUD/Resources.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/GoToGenesisPlazaHUD/Resources/GoToGenesisPlazaHUD.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/GoToGenesisPlazaHUD/Resources/GoToGenesisPlazaHUD.prefab.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Resources/Taskbar.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/TaskbarHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/TaskbarHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Tests/TaskbarHUDShould.cs
  unity-client/Assets/Tutorial/Prefabs/Resources/TutorialController.prefab
  unity-client/Assets/Tutorial/Prefabs/Steps/TutorialStep_TaskbarTooltip_RestartTutorial.prefab
  unity-client/Assets/Tutorial/Prefabs/Steps/TutorialStep_TaskbarTooltip_RestartTutorial.prefab.meta
  unity-client/Assets/Tutorial/Scripts/Steps/TutorialStep_GenesisGreetings.cs
  unity-client/Assets/Tutorial/Scripts/Steps/TutorialStep_Tooltip_RestartTutorialButton.cs
  unity-client/Assets/Tutorial/Scripts/Steps/TutorialStep_Tooltip_RestartTutorialButton.cs.meta
  unity-client/Assets/Tutorial/Scripts/Tutorial.asmdef
  unity-client/Assets/Tutorial/Scripts/TutorialController.cs
  unity-client/Assets/Tutorial/Tests/TutorialControllerShould.cs
Labels: wip

#1522 fix: exiting from an AvatarModifier volume is handled properly
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarModifiers/AvatarModifierArea.cs
Labels: ready for review

#1526 fix: "View Profile" text on invisible avatars
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.cs
Labels: ready for review

#1525 fix: sdk moveplayer scene reload
  kernel/packages/shared/world/parcelSceneManager.ts
Labels: ready for review

#1515 fix: worker update error handling
  kernel/packages/entryPoints/unity.ts
  kernel/packages/scene-system/scene.system.ts
  kernel/packages/shared/world/CustomWebWorkerTransport.ts
  kernel/packages/shared/world/SceneWorker.ts
Labels: bug, ready for review

#1527 feat: navmap chunks are loaded from start
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/MapChunk.cs
Labels: ready for review

#1530 feat: add contextmenu to users around list
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/UsersAroundListHUD/Prefabs/UsersListElement.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/UsersAroundListHUD/Resources/UsersAroundListHUD.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/UsersAroundListHUD/UsersAroundListHUD.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/UsersAroundListHUD/UsersAroundListHUDListElementView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/UsersAroundListHUD/UsersAroundListHUDListView.cs
Labels: ready for review
