Repository decentraland/explorer, pull requests merged in 2020-07, with the labels that each got.

#1059 fix: Performance Improvements (II)
  unity-client/Assets/Scenes/InitialScene.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Audio/DCLAudioClip.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Audio/DCLAudioSource.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Audio/DCLAudioStream.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Textures/DCLTexture.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Video/DCLVideoTexture.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Video/Plugins/WebVideoPlayer.jslib
Labels: ready for review

#1018 fix: profiling panel issues
  unity-client/Assets/Resources/Prefabs/SceneController.prefab
  unity-client/Assets/Scenes/InitialScene.unity
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB/AssetPromise_AB.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Rendering/RenderingController.cs
  unity-client/Assets/Scripts/MainScripts/Debugging/Panels/MessageBenchmarkController.cs
  unity-client/Assets/Scripts/MainScripts/Debugging/Panels/MiscBenchmarkController.cs
  unity-client/Assets/Scripts/MainScripts/Debugging/Panels/StatsPanelToggler.cs
  unity-client/Assets/Scripts/MainScripts/MainScripts.asmdef
Labels: ready for review

#1052 feat: asset promise keeper for textures
  kernel/packages/decentraland-ecs/src/decentraland/Components.ts
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarRenderer.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/FacialFeatureController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Textures/DCLTexture.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB/AssetPromise_AB.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Common/AssetLibrary_RefCounted.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Common/AssetPromise.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Texture/AssetLibrary_Texture.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Texture/AssetLibrary_Texture.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Texture/AssetPromiseKeeper_Texture.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Texture/AssetPromise_Texture.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Texture/Asset_Texture.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Texture/Tests.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Texture/Tests/APK_Texture_Promise_Should.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Texture/Tests/APK_Texture_Promise_Should.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Texture/Tests/APK_Texture_ShouldWorkWhen.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Texture/Tests/APK_Texture_ShouldWorkWhen.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Texture/Tests/APK_Texture_Tests.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Texture/Tests/APK_Texture_Tests.asmdef.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Texture/Tests/BlockedAndMasterPromisesShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Texture/Tests/BlockedAndMasterPromisesShould.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Tests/AvatarEditorHUDControllerShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Helpers/CoroutineHelpers/CoroutineStarter.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Helpers/ThumbnailsManager/ThumbnailsManager.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Helpers/ThumbnailsManager/ThumbnailsManager.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Helpers/Utils/Utils.cs
Labels: ready for review

#1074 feat: Updated peer library to use relay suspension protocol
  kernel/package-lock.json
  kernel/package.json
  kernel/packages/shared/comms/index.ts
  kernel/packages/shared/meta/index.ts
  kernel/packages/shared/meta/types.ts
Labels: ready for review

#1075 feat: Improve Loading Screen Feedback
  kernel/packages/shared/loading/actions.ts
  kernel/packages/shared/loading/reducer.ts
  kernel/packages/shared/loading/sagas.ts
  kernel/packages/unity-interface/dcl.ts
  unity-client/Assets/Resources/Prefabs/SceneController.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB/AssetPromise_AB.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/LoadingFeedbackController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/LoadingFeedbackController.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MessagingBus.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/ParcelScene.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/SceneController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
  unity-client/Assets/UnityGLTF/Scripts/GLTFComponent.cs
Labels: ready for review

#1068 fix: remove IDB caching for unity requests
  kernel/packages/shared/meta/sagas.ts
  kernel/packages/shared/meta/types.ts
  kernel/packages/unity-interface/initializer.ts
  unity-client/Assets/Plugins/WebGLCachedXMLHttpRequest/WebGLCachedXMLHttpRequest.jspre
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/LoadWrapper/RendereableAssetLoadHelper.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB/AssetPromise_AB.cs
Labels: ready for review

#1080 fix: Improve performance on DepMap persistent cache savings
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/DependencyMapLoadHelper.cs
Labels: ready for review

#1081 fix: performance drop on expression animation call
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Tests/AvatarEditorHUDControllerShould.cs
Labels: ready for review

#1090 fix: avatar name size in retina display
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.prefab
Labels: ready for review

#1065 fix: pointer lock
  kernel/packages/unity-interface/dcl.ts
  unity-client/Assets/Scripts/MainScripts/DCL/Helpers/MouseCatcher/MouseCatcher.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Helpers/Utils/Utils.cs
Labels: merge me!, ready for review

#1095 fix: weird dithering AA
  unity-client/Assets/Scenes/InitialScene.unity
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Camera/Resources/CameraController.prefab
Labels: ready for review

#1089 feat: chat message when friend goes online
  kernel/packages/shared/chat/private.ts
  kernel/packages/shared/comms/chat.ts
Labels: ready for review

#1093 fix: add hiccup metrics
  unity-client/Assets/Scripts/MainScripts/Debugging/FPSDisplay.cs
Labels: ready for review

#1094 chore: bump depmap cache key
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/DependencyMapLoadHelper.cs
Labels: ready for review

#1096 chore: re-enable PP in camera
  .circleci/config.yml
  unity-client/Assets/Scenes/InitialScene.unity
Labels: ready for review

#1099 fix: stuck local build issue
  .circleci/config.yml
  .circleci/hotpatch.sh
  kernel/static/unity/Build/DCLUnityLoader.js
  unity-client/Assets/Plugins/DCL_CachedXHR.meta
  unity-client/Assets/Plugins/DCL_CachedXHR/DCL_CachedXHR.jspre
  unity-client/Assets/Plugins/DCL_CachedXHR/DCL_CachedXHR.jspre.meta
  unity-client/Assets/Plugins/DCL_CachedXHR/readme.txt
  unity-client/Assets/Plugins/DCL_CachedXHR/readme.txt.meta
Labels: merge me!

#1104 fix: Sometimes UI Images UV is not being well configured
  unity-client/Assets/Scripts/MainScripts/DCL/Components/UI/UIImage/UIImage.cs
Labels: merge me!

#1106 fix: Make Loading Screen feedback more intuitive
  kernel/packages/shared/loading/types.ts
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/LoadingFeedbackController.cs
Labels: ready for review

#1098 fix: Improve the disposable components cleaning
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Audio/DCLAudioClip.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/BaseDisposable.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Font/DCLFont.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Materials/BasicMaterial.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Materials/PBRMaterial.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Textures/DCLTexture.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/UI/UIContainer/UIContainerRect.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/UI/UIContainer/UIContainerStack.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/UI/UIImage/UIImage.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/UI/UIScrollRect/UIScrollRect.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/UI/UIText/UIText.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Video/DCLVideoTexture.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/MemoryManager/MemoryManager.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/ParcelScene.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/ParcelScenesCleaner.cs
  unity-client/Packages/manifest.json
Labels: ready for review

#1107 fix: typo in ControlsHUDView prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ControlsHUD/Resources/ControlsHUD.prefab
Labels: ready for review

#1109 fix: Make Loading Screen feedback more intuitive (II)
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/LoadingFeedbackController.cs
Labels: wip

#1110 fix: Prevent the progress percentage decrease during the loading
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/LoadingFeedbackController.cs
Labels: ready for review

#1088 feat: avatars pooling
  kernel/packages/shared/profiles/transformations/processServerProfile.ts
  unity-client/Assets/Builder/Scripts/DCLBuilderBridge.cs
  unity-client/Assets/Resources/Prefabs/SceneController.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Audio/Tests/AudioTests.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarAnimatorLegacy.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarMovementController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarName.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarRenderer.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarUtils.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/BodyShapeController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/Tests/AvatarShape_Helpers.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/Tests/WearableItemsShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/WearableController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/BaseComponent.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/BaseDisposable.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/ComponentUpdateHandler.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Textures/DCLTexture.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/UUIDComponent/OnPointerEvent.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/UUIDComponent/OnPointerEventColliders.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Common/Tests/APKWithRefCountedAssetShouldWorkWhen_Base.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/CharacterPreviewController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/ItemToggleFactory.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Tests/AvatarEditorHUDControllerShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExpressionsHUD/ExpressionsHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationHUD/Notification.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/MemoryManager/MemoryManager.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/PlayerAvatarController/PlayerAvatarController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/PoolManager/IPoolLifecycleHandler.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/PoolManager/IPoolLifecycleHandler.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/PoolManager/Pool.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/PoolManager/PoolableObject.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/BlockerHandler.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/ParcelScene.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/ParcelScenesCleaner.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/SceneController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Factory/DCLComponentFactory.asset
  unity-client/Assets/Scripts/MainScripts/DCL/Factory/DCLComponentFactory.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Models/AvatarModel/AvatarModel.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Models/DecentralandEntity.cs
  unity-client/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfile.cs
  unity-client/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
  unity-client/Assets/Scripts/Tests/TestHelpers.cs
Labels: ready for review

#1113 fix: Make the Loading Bar realistic
  kernel/packages/entryPoints/unity.ts
  kernel/packages/shared/loading/actions.ts
  kernel/packages/shared/loading/reducer.ts
  kernel/packages/shared/loading/sagas.ts
  kernel/packages/shared/loading/types.ts
  kernel/packages/unity-interface/dcl.ts
  kernel/static/index.html
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/LoadingFeedbackController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
Labels: ready for review

#1117 fix: avatar eyes issues
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarRenderer.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/BodyShapeController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/FacialFeatureController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/WearableController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Texture/AssetPromise_Texture.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/MapChunk.cs
Labels: ready for review

#1120 fix: List.Contains cpu spike
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Common/AssetPromiseKeeper.cs
Labels: ready for review

#1124 fix: avatar editor thumbnail issues
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Common/AssetLibrary_RefCounted.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Texture/AssetLibrary_Texture.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Texture/AssetPromise_Texture.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Texture/Asset_Texture.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AirdroppingHUD/AirdroppingHUD.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AirdroppingHUD/AirdroppingItemPanel.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/ItemToggle.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/NFTItemInfo.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/PlayerInfoCardHUD.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/PlayerInfoCollectibleItem.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Helpers/TextureHelpers/TextureHelpers.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Helpers/ThumbnailsManager/ThumbnailsManager.cs
  unity-client/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfile.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfile.cs
  unity-client/Assets/Scripts/MainScripts/MainScripts.asmdef
Labels: ready for review

#1119 chore: tweak hiccup metric (part 2)
  kernel/packages/unity-interface/dcl.ts
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/Spinner/LoadingSpinner.mat
  unity-client/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
  unity-client/Assets/Scripts/MainScripts/Debugging/FPSDisplay.cs
  unity-client/Assets/Scripts/MainScripts/Debugging/FPSDisplay.meta
  unity-client/Assets/Scripts/MainScripts/Debugging/FPSDisplay/FPSColor.cs
  unity-client/Assets/Scripts/MainScripts/Debugging/FPSDisplay/FPSColor.cs.meta
  unity-client/Assets/Scripts/MainScripts/Debugging/FPSDisplay/FPSColoring.cs
  unity-client/Assets/Scripts/MainScripts/Debugging/FPSDisplay/FPSColoring.cs.meta
  unity-client/Assets/Scripts/MainScripts/Debugging/FPSDisplay/FPSDisplay.asmdef
  unity-client/Assets/Scripts/MainScripts/Debugging/FPSDisplay/FPSDisplay.asmdef.meta
  unity-client/Assets/Scripts/MainScripts/Debugging/FPSDisplay/FPSDisplay.cs
  unity-client/Assets/Scripts/MainScripts/Debugging/FPSDisplay/FPSDisplay.cs.meta
  unity-client/Assets/Scripts/MainScripts/Debugging/FPSDisplay/FPSEvaluation.cs
  unity-client/Assets/Scripts/MainScripts/Debugging/FPSDisplay/FPSEvaluation.cs.meta
  unity-client/Assets/Scripts/MainScripts/Debugging/FPSDisplay/LinealBufferFPSCounter.cs
  unity-client/Assets/Scripts/MainScripts/Debugging/FPSDisplay/LinealBufferFPSCounter.cs.meta
  unity-client/Assets/Scripts/MainScripts/Debugging/FPSDisplay/LinealBufferHiccupCounter.cs
  unity-client/Assets/Scripts/MainScripts/Debugging/FPSDisplay/LinealBufferHiccupCounter.cs.meta
  unity-client/Assets/Scripts/MainScripts/Debugging/FPSDisplay/Tests.meta
  unity-client/Assets/Scripts/MainScripts/Debugging/FPSDisplay/Tests/FPSDisplayTests.asmdef
  unity-client/Assets/Scripts/MainScripts/Debugging/FPSDisplay/Tests/FPSDisplayTests.asmdef.meta
  unity-client/Assets/Scripts/MainScripts/Debugging/FPSDisplay/Tests/FPSDisplayTests.cs
  unity-client/Assets/Scripts/MainScripts/Debugging/FPSDisplay/Tests/FPSDisplayTests.cs.meta
  unity-client/Assets/Scripts/MainScripts/Debugging/FPSDisplay/Tests/HiccupTests.cs
  unity-client/Assets/Scripts/MainScripts/Debugging/FPSDisplay/Tests/HiccupTests.cs.meta
  unity-client/Assets/Scripts/MainScripts/Debugging/PerformanceMetricsController.cs
  unity-client/Assets/Scripts/MainScripts/MainScripts.asmdef
Labels: ready for review

#1130 refactor: avoid modifying DOM when values are equal
  kernel/packages/shared/loading/sagas.ts
Labels: ready for review

#1132 chore: use action payload to report scenes around parcel
  kernel/packages/shared/atlas/sagas.ts
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/NavmapView.cs
Labels: ready for review

#1128 fix: "can't reparent transform while its being disabled" exception
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarRenderer.cs
Labels: ready for review

#1135 chore: add action to report scenes to engine using parcel coordinates
  kernel/packages/shared/atlas/actions.ts
  kernel/packages/shared/atlas/sagas.ts
Labels: ready for review

#1131 fix: transparency order issues
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarUtils.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Helpers/MaterialHelpers/SRPBatchingHelper/SRPBatchingHelper.cs
Labels: ready for review

#1129 fix: AssetPromise_AB_GameObject not failing correctly
  unity-client/.gitignore
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB/AssetPromise_AB.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB_GameObject/AssetPromise_AB_GameObject.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB_GameObject/Tests/APK_AB_GameObject_Promise_Should.cs
  unity-client/Assets/Scripts/MainScripts/Debugging/FPSDisplay/Tests/HiccupTests.cs
  unity-client/TestResources/AssetBundles/Broken_paladin_AB
Labels: ready for review

#1134 fix: ensure unique ids for videos
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Video/DCLVideoTexture.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Video/Plugins/WebVideoPlayer.jslib
Labels: ready for review

#1137 fix: avatar glitches when wearables are missing from profile
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarRenderer.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarUtils.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/BodyShapeController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/WearableController.cs
Labels: ready for review

#1136 feat: explore -part1- fetch hotscenes
  kernel/packages/decentraland-loader/lifecycle/utils/fetchSceneIds.ts
  kernel/packages/decentraland-loader/lifecycle/utils/fetchSceneJson.ts
  kernel/packages/shared/atlas/sagas.ts
  kernel/packages/shared/chat/sagas.ts
  kernel/packages/shared/social/hotScenes.ts
Labels: ready for review

#1116 feat: loading screen improvements initial load
  kernel/package-lock.json
  kernel/package.json
  kernel/packages/config/contracts.ts
  kernel/packages/decentraland-loader/lifecycle/manager.ts
  kernel/packages/decentraland-loader/lifecycle/worker.ts
  kernel/packages/entryPoints/preview.ts
  kernel/packages/entryPoints/unity.ts
  kernel/packages/shared/analytics/sagas.ts
  kernel/packages/shared/apis/UserIdentity.ts
  kernel/packages/shared/atlas/sagas.ts
  kernel/packages/shared/chat/actions.ts
  kernel/packages/shared/chat/reducer.ts
  kernel/packages/shared/chat/sagas.ts
  kernel/packages/shared/chat/selectors.ts
  kernel/packages/shared/chat/types.ts
  kernel/packages/shared/comms/chat.ts
  kernel/packages/shared/comms/index.ts
  kernel/packages/shared/comms/reducer.ts
  kernel/packages/shared/comms/sagas.ts
  kernel/packages/shared/comms/types.ts
  kernel/packages/shared/dao/sagas.ts
  kernel/packages/shared/ethereum/provider.ts
  kernel/packages/shared/friends/actions.ts
  kernel/packages/shared/friends/reducer.ts
  kernel/packages/shared/friends/sagas.ts
  kernel/packages/shared/friends/selectors.ts
  kernel/packages/shared/friends/types.ts
  kernel/packages/shared/index.ts
  kernel/packages/shared/loading/sagas.ts
  kernel/packages/shared/meta/sagas.ts
  kernel/packages/shared/profiles/sagas.ts
  kernel/packages/shared/profiles/transformations/profileToRendererFormat.ts
  kernel/packages/shared/renderer/actions.ts
  kernel/packages/shared/renderer/index.ts
  kernel/packages/shared/renderer/reducer.ts
  kernel/packages/shared/renderer/sagas.ts
  kernel/packages/shared/renderer/types.ts
  kernel/packages/shared/session/actions.ts
  kernel/packages/shared/session/index.ts
  kernel/packages/shared/session/reducer.ts
  kernel/packages/shared/session/sagas.ts
  kernel/packages/shared/session/selectors.ts
  kernel/packages/shared/session/types.ts
  kernel/packages/shared/store/rootReducer.ts
  kernel/packages/shared/store/rootSaga.ts
  kernel/packages/shared/store/rootTypes.ts
  kernel/packages/shared/world/TeleportController.ts
  kernel/packages/unity-interface/dcl.ts
  kernel/packages/unity-interface/initializer.ts
  kernel/static/index.html
  kernel/static/preview.html
  kernel/test/unit/profiles.saga.test.tsx
Labels: ready for review

#1141 fix: Improve AssetBundles loading performance
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB/AssetBundlesLoader.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB/AssetBundlesLoader.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB/AssetPromise_AB.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB_GameObject/AssetPromise_AB_GameObject.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/PoolManager/Pool.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/PoolManager/PoolManager.cs
Labels: ready for review

#1142 fix: Improve AssetBundles loading performance (Part 2)
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB/AssetBundlesLoader.cs
Labels: ready for review

#1144 fix: private chat not displaying timestamp toast
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/Resources/PrivateChatWindow.prefab
Labels: ready for review

#1145 fix: chat heads container not expanding with it content
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/ChatHeadGroupView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Resources/Taskbar.prefab
Labels: ready for review

#1152 fix: taskbar destroy unsubscribe events
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/TaskbarHUDView.cs
Labels: ready for review
