Repository decentraland/explorer, pull requests merged in 2020-11, with the labels that each got.

#1538 fix: billboard and textshape missing null checks
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Billboard/Billboard.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/TextShape/TextShape.cs
Labels: ready for review

#1540 feat: add voicechat settings
  kernel/packages/unity-interface/BrowserInterface.ts
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsHUD/Resources/SettingsHUD.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsHUD/SettingsGeneralView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsHUD/SettingsHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Settings/Settings.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Settings/Settings.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Settings/SettingsControllers/GeneralSettingsController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
Labels: merge me!, ready for review

#1532 fix: changes in bodyshapes now are reflected in wearables representation
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarRenderer.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/BodyShapeController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/Tests/AvatarRendererShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/Tests/AvatarShape_Helpers.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/Tests/WearableControllerShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/WearableController.cs
  unity-client/TestResources/Avatar/TestCatalog.json
Labels: ready for review

#1548 style: change mute all switch color
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/UsersAroundListHUD/SwitchToggle/Animations/switchOFF.anim
Labels: ready for review

#1549 fix: use CoroutineStarter in UsersAroundListHUD
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/UsersAroundListHUD/UsersAroundListHUDListElementView.cs
Labels: ready for review

#1541 fix: simplify FPS metrics
  kernel/packages/entryPoints/unity.ts
  kernel/packages/shared/comms/index.ts
  kernel/packages/shared/friends/sagas.ts
  kernel/packages/shared/world/SceneWorker.ts
  kernel/packages/shared/world/parcelSceneManager.ts
  kernel/packages/shared/world/worldState.ts
  kernel/packages/unity-interface/BrowserInterface.ts
  kernel/packages/unity-interface/dcl.ts
  kernel/packages/unity-interface/delightedSurvey.ts
  unity-client/Assets/Scenes/InitialScene.unity
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/SceneController.cs
  unity-client/Assets/Scripts/MainScripts/Debugging/PerformanceMetricsController.cs
Labels: ready for review

#1550 UI mini improvements
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/Resources/Chat Widget.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Resources/Taskbar.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/Resources/WelcomeHUD.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/Resources/WelcomeHUDButton.prefab
Labels: ready for review

#1535 feat: send kernel configurations to unity
  kernel/packages/shared/types.ts
  kernel/packages/unity-interface/UnityInterface.ts
  kernel/packages/unity-interface/dcl.ts
  kernel/packages/unity-interface/kernelConfigForRenderer.ts
  unity-client/Assets/Scenes/InitialScene.unity
  unity-client/Assets/Scripts/MainScripts/DCL/Bridges/Bridges.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Bridges/Bridges.prefab.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Bridges/KernelConfigurationBridge.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Bridges/KernelConfigurationBridge/KernelConfigurationBridge.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Bridges/KernelConfigurationBridge/KernelConfigurationBridge.asmdef.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Bridges/KernelConfigurationBridge/KernelConfigurationBridge.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Bridges/KernelConfigurationBridge/KernelConfigurationBridge.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/KernelConfiguration.meta
  unity-client/Assets/Scripts/MainScripts/DCL/KernelConfiguration/AssemblyInfo.cs
  unity-client/Assets/Scripts/MainScripts/DCL/KernelConfiguration/AssemblyInfo.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/KernelConfiguration/KernelConfig.cs
  unity-client/Assets/Scripts/MainScripts/DCL/KernelConfiguration/KernelConfig.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/KernelConfiguration/KernelConfigModel.cs
  unity-client/Assets/Scripts/MainScripts/DCL/KernelConfiguration/KernelConfigModel.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/KernelConfiguration/KernelConfigTypes.cs
  unity-client/Assets/Scripts/MainScripts/DCL/KernelConfiguration/KernelConfigTypes.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/KernelConfiguration/KernelConfiguration.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/KernelConfiguration/KernelConfiguration.asmdef.meta
  unity-client/Assets/Scripts/MainScripts/DCL/KernelConfiguration/Resources.meta
  unity-client/Assets/Scripts/MainScripts/DCL/KernelConfiguration/Resources/KernelConfiguration.asset
  unity-client/Assets/Scripts/MainScripts/DCL/KernelConfiguration/Resources/KernelConfiguration.asset.meta
  unity-client/Assets/Scripts/MainScripts/DCL/KernelConfiguration/Tests.meta
  unity-client/Assets/Scripts/MainScripts/DCL/KernelConfiguration/Tests/KernelConfigurationShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/KernelConfiguration/Tests/KernelConfigurationShould.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/KernelConfiguration/Tests/KernelConfigurationTests.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/KernelConfiguration/Tests/KernelConfigurationTests.asmdef.meta
  unity-client/Assets/Scripts/MainScripts/Debugging/WSS/WSSController.cs
Labels: ready for review

#1559 feat: ProfileHUD -> Add Terms and Conditions
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ProfileHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ProfileHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Resources/ProfileHUD.prefab
Labels: ready for review

#1564 [ProfileHUD] Move the Backpack feature into the ProfileHUD
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ProfileHUD.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ProfileHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ProfileHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Resources/ProfileHUD.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Tests/ProfileHUDTests.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Tests/ProfileHUDTests.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/TaskbarHUD.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/TaskbarHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/TaskbarHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Tests/TaskbarHUDShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Tests/TaskbarHUDTests.asmdef
  unity-client/Assets/Tutorial/Prefabs/Steps/TutorialStep_TaskbarTooltip_BackpackButton.prefab
  unity-client/Assets/Tutorial/Scripts/Steps/TutorialStep_BasicControls.cs
  unity-client/Assets/Tutorial/Scripts/Steps/TutorialStep_GenesisGreetings.cs
  unity-client/Assets/Tutorial/Scripts/Steps/TutorialStep_GenesisGreetingsAfterDeepLink.cs
  unity-client/Assets/Tutorial/Scripts/Steps/TutorialStep_LockTheCursor.cs
  unity-client/Assets/Tutorial/Scripts/Steps/TutorialStep_OpenControlsPanel.cs
  unity-client/Assets/Tutorial/Scripts/Steps/TutorialStep_Tooltip_BackpackButton.cs
  unity-client/Assets/Tutorial/Scripts/TutorialController.cs
Labels: wip

#1567 Beta label added on Settings Panel for Voice chat
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsHUD/Resources/SettingsHUD.prefab
Labels: ready for review

#1551 chore: engine getcomponent optimization
  kernel/packages/decentraland-ecs/src/ecs/Engine.ts
  kernel/test/index.ts
  kernel/test/unit/engine.test.tsx
Labels: ready for review

#1568 feat: add screen for when UsersAroundListHUD list is empty
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Resources/Taskbar.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/UsersAroundListHUD/IUsersAroundListHUDListView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/UsersAroundListHUD/Resources/UsersAroundListHUD.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/UsersAroundListHUD/Textures/CrowdIcon.png
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/UsersAroundListHUD/Textures/CrowdIcon.png.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/UsersAroundListHUD/UsersAroundListHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/UsersAroundListHUD/UsersAroundListHUDListView.cs
Labels: ready for review

#1566 fix: invalid fps stacking when out of focus
  kernel/packages/entryPoints/unity.ts
  kernel/packages/shared/world/worldState.ts
  kernel/packages/unity-interface/BrowserInterface.ts
  kernel/packages/unity-interface/UnityInterface.ts
  unity-client/Assets/Resources/ScriptableObjects/FocusState.asset
  unity-client/Assets/Resources/ScriptableObjects/FocusState.asset.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Bridges/Bridges.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Bridges/FocusStateBridge.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Bridges/FocusStateBridge/FocusStateBridge.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Bridges/FocusStateBridge/FocusStateBridge.asmdef.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Bridges/FocusStateBridge/FocusStateBridge.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Bridges/FocusStateBridge/FocusStateBridge.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/ScriptableObject/CommonScriptableObjects.cs
  unity-client/Assets/Scripts/MainScripts/Debugging/PerformanceMetricsController.cs
  unity-client/Assets/Scripts/MainScripts/Debugging/WSS/WSSController.asmdef
  unity-client/Assets/Scripts/MainScripts/Debugging/WSS/WSSController.cs
Labels: ready for review

#1560 fix: nullreference exception when stopping editor
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/UsersAroundListHUD/UsersAroundListHUDListView.cs
Labels: merge me!, ready for review

#1570 [ProfileHUD] Add "SignUp" button into ProfileHUD
  kernel/packages/entryPoints/unity.ts
  kernel/packages/entryPoints/website.ts
  kernel/packages/shared/session/actions.ts
  kernel/packages/shared/session/index.ts
  kernel/packages/shared/session/sagas.ts
  kernel/packages/unity-interface/BrowserInterface.ts
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/EmailPromptHUD/EmailPromptHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ProfileHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ProfileHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Resources/ProfileHUD.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Tests/ProfileHUDTests.cs
  unity-client/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
Labels: wip

#1575 refactor: unity's KernelConfig remove use of scriptable object
  unity-client/Assets/Scripts/MainScripts/DCL/KernelConfiguration/KernelConfig.cs
  unity-client/Assets/Scripts/MainScripts/DCL/KernelConfiguration/Resources.meta
  unity-client/Assets/Scripts/MainScripts/DCL/KernelConfiguration/Resources/KernelConfiguration.asset
  unity-client/Assets/Scripts/MainScripts/DCL/KernelConfiguration/Resources/KernelConfiguration.asset.meta
  unity-client/Assets/Scripts/MainScripts/DCL/KernelConfiguration/Tests/KernelConfigurationShould.cs
Labels: ready for review

#1531 fix: SRP batching helper improvements
  unity-client/Assets/Materials/Ground.mat
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Materials/BasicMaterial.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Materials/PBRMaterial.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Helpers/MaterialHelpers/MaterialCachingHelper/MaterialCachingHelper.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Helpers/MaterialHelpers/SRPBatchingHelper/SRPBatchingHelper.cs
  unity-client/Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs
Labels: ready for review

#1577 fix: pbrmaterial missing null check
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Materials/PBRMaterial.cs
Labels: ready for review

#1576 fix: add blocked user indicator on usersaroundlisthud
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/UsersAroundListHUD/IUsersAroundListHUDListView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/UsersAroundListHUD/Prefabs/UsersListElement.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/UsersAroundListHUD/UsersAroundListHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/UsersAroundListHUD/UsersAroundListHUDListElementView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/UsersAroundListHUD/UsersAroundListHUDListView.cs
Labels: ready for review

#1573 chore: documentation for InputController
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/InputController/InputAction_Hold.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/InputController/InputAction_Measurable.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/InputController/InputAction_Trigger.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/InputController/InputController.cs
Labels: ready for review

#1580 fix: wearablecontroller missing null check
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/WearableController.cs
Labels: ready for review

#1578 [ProfileHUD] Edit avatar name
  kernel/packages/shared/profiles/sagas.ts
  kernel/packages/shared/profiles/transformations/processServerProfile.ts
  kernel/packages/unity-interface/BrowserInterface.ts
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ProfileHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ProfileHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Resources/ProfileHUD.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Tests/ProfileHUDTests.cs
  unity-client/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
Labels: ready for review

#1588 [ProfileHUD] Fix LogOut flow
  kernel/packages/shared/session/index.ts
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Resources/ProfileHUD.prefab
Labels: ready for review

#1554 [ProfileHUD] Changes for the new SignIn flow
  kernel/packages/entryPoints/unity.ts
  kernel/packages/entryPoints/website.ts
  kernel/packages/shared/profiles/sagas.ts
  kernel/packages/shared/profiles/transformations/processServerProfile.ts
  kernel/packages/shared/session/actions.ts
  kernel/packages/shared/session/index.ts
  kernel/packages/shared/session/sagas.ts
  kernel/packages/shared/types.ts
  kernel/packages/unity-interface/BrowserInterface.ts
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/EmailPromptHUD/EmailPromptHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ManaHUD.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ManaHUD/AssemblyInfo.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ManaHUD/AssemblyInfo.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ManaHUD/ManaHUD.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ManaHUD/ManaHUD.asmdef.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ManaHUD/ManaHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ManaHUD/ManaHUDview.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ManaHUD/ManaHUDview.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ManaHUD/Resources.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ManaHUD/Resources/ManaHUD.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ManaHUD/Resources/ManaHUD.prefab.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ManaHUD/Test.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ManaHUD/Test/ManaHUDTest.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ManaHUD/Test/ManaHUDTest.asmdef.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ManaHUD/Test/ManaHUDTest.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ManaHUD/Test/ManaHUDTest.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ManaCounterView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ManaCounterView.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ProfileHUD.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ProfileHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ProfileHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Resources/ProfileHUD.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Tests/ProfileHUDTests.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Tests/ProfileHUDTests.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Resources/Taskbar.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/TaskbarHUD.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/TaskbarHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/TaskbarHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Tests/TaskbarHUDShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Tests/TaskbarHUDTests.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
  unity-client/Assets/Tutorial/Prefabs/Steps/TutorialStep_TaskbarTooltip_BackpackButton.prefab
  unity-client/Assets/Tutorial/Scripts/Steps/TutorialStep_BasicControls.cs
  unity-client/Assets/Tutorial/Scripts/Steps/TutorialStep_GenesisGreetings.cs
  unity-client/Assets/Tutorial/Scripts/Steps/TutorialStep_GenesisGreetingsAfterDeepLink.cs
  unity-client/Assets/Tutorial/Scripts/Steps/TutorialStep_LockTheCursor.cs
  unity-client/Assets/Tutorial/Scripts/Steps/TutorialStep_OpenControlsPanel.cs
  unity-client/Assets/Tutorial/Scripts/Steps/TutorialStep_Tooltip_BackpackButton.cs
  unity-client/Assets/Tutorial/Scripts/TutorialController.cs
Labels: ready for review

#1592 fix: Updates circleci to deploy after website was build
  .circleci/config.yml
Labels: ready for review

#1593 fix: removes set hash version to unity.js
  kernel/scripts/prepareDist.ts
Labels: ready for review

#1594 Fix filters public_url for react app when branch is master, staging or release
  .circleci/config.yml
Labels: ready for review

#1597 chore: add build profiling info in readme
  README.md
Labels: ready for review

#1563 fix: hover feedback when blocked by ui
  unity-client/Assets/Scripts/MainScripts/DCL/Components/UI/UIScreenSpace/UIScreenSpace.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/PointerEventsController.cs
  unity-client/Assets/Scripts/Tests/CursorControllerTests/CursorControllerTests.cs
Labels: ready for review

#1607 fix: website pre-start.js symlink windows issue
  website/scripts/pre-start.js
Labels: ready for review

#1601 chore: new reflection map
  unity-client/Assets/Rendering/Profiles/Default/Reflection/CubemapPlaza.jpg
  unity-client/Assets/Rendering/Profiles/Default/Reflection/CubemapPlaza.png
  unity-client/Assets/Rendering/Profiles/Default/Reflection/CubemapPlaza.png.meta
  unity-client/Assets/Rendering/Profiles/Default/Resources/Default World.asset
  unity-client/Assets/Rendering/Profiles/Test/Resources/Test World.asset
Labels: ready for review

#1606 fix: avatar random color issue
  unity-client/Assets/Rendering/Shaders/URP/Lit.shader
Labels: ready for review

#1602 fix: Sign in buttons unresponsive when loading started
  kernel/packages/shared/renderer/sagas.ts
  kernel/packages/unity-interface/dcl.ts
  website/public/index.html
  website/src/store/index.ts
Labels: do not merge

#1599 fix: Tutorial is activated too late after the new SignUp flow
  kernel/package-lock.json
  kernel/packages/entryPoints/website.ts
  kernel/packages/shared/loading/reducer.ts
  kernel/packages/shared/loading/selectors.ts
  kernel/packages/shared/loading/types.ts
  kernel/packages/shared/session/sagas.ts
  kernel/packages/shared/world/TeleportController.ts
  kernel/packages/unity-interface/BrowserInterface.ts
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsHUD/SettingsHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsHUD/Test/SettingsHUDControllerShould.cs
  website/src/components/loading/LoadingContainer.tsx
Labels: ready for review

#1610 fix: The MANA HUD is always initialized with balance 0
  kernel/packages/entryPoints/website.ts
Labels: ready for review

#1600 feat: graphic card warning feature
  kernel/packages/entryPoints/website.ts
  kernel/packages/shared/types.ts
  unity-client/Assets/Plugins/JSFunctions.jslib
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/GraphicCardWarningHUD.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/GraphicCardWarningHUD/GraphicCardNotification.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/GraphicCardWarningHUD/GraphicCardNotification.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/GraphicCardWarningHUD/GraphicCardWarningHUD.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/GraphicCardWarningHUD/GraphicCardWarningHUD.asmdef.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/GraphicCardWarningHUD/GraphicCardWarningHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/GraphicCardWarningHUD/GraphicCardWarningHUDController.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/GraphicCardWarningHUD/GraphicCardWarningNotification.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/GraphicCardWarningHUD/GraphicCardWarningNotification.prefab.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUD.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationHUD/NotificationFactory.asset
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationHUD/NotificationFactory.cs
  unity-client/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
  unity-client/Assets/Shaders.meta
Labels: merge me!, ready for review

#1604 fix: avatar walking animation stutter
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarAnimatorLegacy.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/DCLCharacterController.cs
Labels: merge me!, ready for review

#1579 feat: voicechat animation in avatar shape
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarName.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarName/Animations.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarName/Animations/VoiceIconController.controller
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarName/Animations/VoiceIconController.controller.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarName/Animations/VoiceIconIn.anim
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarName/Animations/VoiceIconIn.anim.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarName/Animations/VoiceIconOut.anim
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarName/Animations/VoiceIconOut.anim.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarName/Animations/VoiceIconTalking.anim
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarName/Animations/VoiceIconTalking.anim.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarName/AvatarName.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarName/AvatarName.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarName/AvatarName.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarName/AvatarName.prefab.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.prefab
  unity-client/Assets/Textures/UI/RectangleGreen.png
  unity-client/Assets/Textures/UI/RectangleGreen.png.meta
Labels: ready for review

#1618 fix: getProfileType circular dependency
  kernel/packages/entryPoints/editor.ts
  kernel/packages/shared/comms/index.ts
  kernel/packages/shared/comms/peers.ts
  kernel/packages/shared/comms/v1/brokerWorldInstanceConnection.ts
  kernel/packages/shared/comms/v2/LighthouseWorldInstanceConnection.ts
  kernel/packages/shared/profiles/getProfileType.ts
  kernel/packages/shared/profiles/sagas.ts
Labels: ready for review

#1605 fix: avatar draw call batch improvements
  unity-client/Assets/Rendering/Shaders/Toon/Compiled/ToonShaderCompiled.shader
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarUtils.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/Shaders/EyesShader.shader
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/Shaders/ToonShader.shader
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/Shaders/UnlitCutoutTinted.shader
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/Shaders/HLSL/NoiseTest.shader
  unity-client/Assets/Scripts/MainScripts/DCL/Helpers/MaterialHelpers/MaterialCachingHelper/MaterialCachingHelper.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Helpers/MaterialHelpers/SRPBatchingHelper/SRPBatchingHelper.cs
Labels: ready for review

#1620 fix: (builder) session related issues
  kernel/packages/entryPoints/editor.ts
  kernel/packages/shared/ethereum/provider.ts
Labels: ready for review

#1630 feat: Adds fake names for guest user
  kernel/packages/shared/profiles/generateRandomUserProfile.ts
  kernel/packages/shared/profiles/transformations/processServerProfile.ts
  kernel/packages/shared/profiles/utils/fakeName.ts
Labels: ready for review

#1628 Chore: website feedback
  website/src/components/auth/EthLogin.tsx
  website/src/components/auth/passport/Passport.tsx
  website/src/components/auth/passport/PassportForm.css
  website/src/components/auth/passport/PassportForm.tsx
  website/src/components/auth/terms/TermsOfServices.tsx
  website/src/components/auth/wallet/WalletSelector.tsx
  website/src/components/common/Navbar.tsx
Labels: ready for review

#1609 Chore: react updates
  README.md
  kernel/packages/shared/world/TeleportController.ts
  website/package-lock.json
  website/package.json
  website/public/index.html
  website/scripts/hash_generator.js
  website/scripts/post-install.sh
  website/scripts/pre-start.js
  website/src/components/auth/EthLogin.stories.tsx
  website/src/components/auth/EthLogin.tsx
  website/src/components/auth/LoginContainer.stories.tsx
  website/src/components/auth/LoginContainer.tsx
  website/src/components/auth/SignUpContainer.tsx
  website/src/components/auth/wallet/WalletButton.css
  website/src/components/auth/wallet/WalletButton.stories.tsx
  website/src/components/auth/wallet/WalletButton.tsx
  website/src/components/auth/wallet/WalletSelector.stories.tsx
  website/src/components/auth/wallet/WalletSelector.tsx
  website/src/components/common/Navbar.tsx
Labels: ready for review

#1613 fix: Only allow alphanumeric characters in names
  kernel/packages/entryPoints/website.ts
  kernel/packages/shared/profiles/transformations/processServerProfile.ts
  kernel/packages/shared/profiles/utils/names.ts
  kernel/packages/shared/types.ts
  kernel/packages/unity-interface/kernelConfigForRenderer.ts
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ProfileHUD.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ProfileHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ProfileHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/KernelConfiguration/KernelConfigModel.cs
  unity-client/Assets/Scripts/MainScripts/DCL/KernelConfiguration/KernelConfigTypes.cs
  unity-client/Assets/Scripts/MainScripts/DCL/KernelConfiguration/Tests/KernelConfigurationShould.cs
  website/src/components/auth/passport/PassportForm.tsx
  website/src/components/types.ts
  website/src/utils/index.ts
Labels: ready for review

#1636 fix: currentSceneId null check on preview and builder
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/PointerEventsController.cs
Labels: ready for review

#1627 fix: Cancel button in AvatarEditorHUD for SignUp flow
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
Labels: ready for review

#1640 fix: Make the GPU warning waits for tutorial ends
  kernel/packages/entryPoints/website.ts
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/GraphicCardWarningHUD/GraphicCardWarningHUDController.cs
Labels: ready for review

#1643 fix: misplaced fps UI position (behind the taskbar)
  unity-client/Assets/Prefabs/FPSPanel.prefab
  unity-client/Assets/Resources/Prefabs/SceneController.prefab
  unity-client/Assets/Scripts/MainScripts/Debugging/Performance/PerformanceMetricsController.cs
Labels: ready for review

#1642 feat: adds link to metamask when user doesn't have it installed
  website/scripts/hash_generator.js
  website/src/components/auth/wallet/WalletSelector.css
  website/src/components/auth/wallet/WalletSelector.tsx
Labels: ready for review

#1633 style: graphic Card Notification styles applied
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/GraphicCardWarningHUD/GraphicCardWarningHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/GraphicCardWarningHUD/GraphicCardWarningNotification.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationHUD/Resources/AirdropNotification.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationHUD/Resources/CommsNotification.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationHUD/Resources/GenericNotification.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationHUD/Resources/GenericWithoutButtonNotification.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationHUD/Resources/Notification.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationHUD/Resources/ScriptingErrorNotification.prefab
Labels: ready for review

#1645 fix: changes when we subscribe to metamask events
  kernel/packages/shared/dao/sagas.ts
  kernel/packages/shared/ethereum/connector/MetamaskConnector.ts
  kernel/packages/shared/web3.ts
Labels: ready for review

#1635 chore: new profile hud style
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ManaCounterView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ProfileHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ProfileHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Resources/ProfileHUD.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Tests/ProfileHUDTests.cs
  unity-client/Assets/Textures/UI/EditIcon.png
  unity-client/Assets/Textures/UI/ProfileHudTopContainer.png
  unity-client/Assets/Textures/UI/ProfileHudTopContainer.png.meta
  unity-client/Assets/Textures/UI/TexturesUI.spriteatlas
Labels: ready for review

#1653 fix: Fix the characters counter in the avatar name edition
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ProfileHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Tests/ProfileHUDTests.cs
Labels: ready for review

#1649 fix: sign in styles
  website/src/components/auth/BeginnersGuide.css
  website/src/components/auth/EthLogin.css
  website/src/components/auth/EthLogin.tsx
  website/src/components/auth/LoginContainer.css
  website/src/components/auth/LoginContainer.stories.tsx
  website/src/components/auth/LoginContainer.tsx
  website/src/components/auth/LoginHeader.tsx
  website/src/components/auth/passport/Passport.css
  website/src/components/auth/passport/Passport.tsx
  website/src/components/auth/passport/PassportAvatar.css
  website/src/components/auth/passport/PassportAvatar.tsx
  website/src/components/auth/passport/PassportForm.css
  website/src/components/auth/passport/PassportForm.tsx
  website/src/components/auth/terms/TermsOfServices.css
  website/src/components/auth/terms/TermsOfServices.tsx
  website/src/components/auth/wallet/WalletButton.css
  website/src/components/auth/wallet/WalletButton.stories.tsx
  website/src/components/auth/wallet/WalletButton.tsx
  website/src/components/auth/wallet/WalletSelector.css
  website/src/components/auth/wallet/WalletSelector.tsx
  website/src/components/common/BigFooter.css
  website/src/components/common/BigFooter.tsx
  website/src/components/common/Container.css
  website/src/components/common/Footer.css
  website/src/components/common/Isologotipo.stories.tsx
  website/src/components/common/Isologotipo.tsx
  website/src/components/common/Logo.css
  website/src/components/common/Logo.stories.tsx
  website/src/components/common/Logo.tsx
  website/src/components/common/Modal.css
  website/src/components/common/Modal.tsx
  website/src/components/common/Navbar.css
  website/src/components/common/Navbar.tsx
  website/src/images/login/background-secondary@1x.jpg
  website/src/images/login/background-secondary@2x.jpg
  website/src/images/login/background-secondary@3x.jpg
  website/src/images/login/background@1x.jpg
  website/src/images/login/background@2x.jpg
  website/src/images/login/background@3x.jpg
  website/src/images/login/fortmatic.svg
  website/src/images/login/isologotipo.svg
  website/src/images/login/metamask.svg
Labels: ready for review

#1658 Fix: website add validation for bad names
  kernel/packages/entryPoints/website.ts
  kernel/packages/shared/profiles/utils/badwords/badWords.ts
  kernel/packages/shared/profiles/utils/badwords/french.ts
  kernel/packages/shared/profiles/utils/badwords/indonesian.ts
  kernel/packages/shared/profiles/utils/badwords/italian.ts
  kernel/packages/shared/profiles/utils/badwords/spanish.ts
  kernel/packages/shared/profiles/utils/badwords/youtube.ts
  kernel/packages/shared/profiles/utils/names.ts
  website/src/components/App.tsx
  website/src/components/auth/passport/PassportForm.tsx
  website/src/components/types.ts
  website/src/utils/index.ts
Labels: ready for review

#1659 chore: replaces guest name list
  kernel/packages/shared/profiles/utils/fakeName.ts
Labels: ready for review

#1663 fix: Make the avatar edition more fluid in the SignUp flow
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MessagingControllersManager.cs
Labels: wip

#1656 chore: disable integrated graphic card warning
  kernel/packages/entryPoints/website.ts
Labels: ready for review

#1664 fix: disable fps prefab
  unity-client/Assets/Resources/Prefabs/SceneController.prefab
Labels: ready for review

#1651 fix: AssetPromise_Texture abort download on cancel
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Texture/AssetPromise_Texture.cs
Labels: ready for review

#1598 chore: add 30 fps cap in settings
  .gitattributes
  kernel/packages/shared/session/getPerformanceInfo.ts
  kernel/packages/unity-interface/BrowserInterface.ts
  kernel/test/unit/getPerformanceInfo.tsx
  unity-client/Assets/Plugins/CustomRequestAnimationFrame.meta
  unity-client/Assets/Plugins/CustomRequestAnimationFrame/CustomRequestAnimationFrame.jspre
  unity-client/Assets/Plugins/CustomRequestAnimationFrame/CustomRequestAnimationFrame.jspre.meta
  unity-client/Assets/Plugins/JSFunctions.jslib
  unity-client/Assets/Plugins/RequestAnimationFrameBackground/RequestAnimationFrameBackground.jspre
  unity-client/Assets/Resources/ScriptableObjects/QualitySettingsData.asset
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsHUD/Resources/SettingsHUD.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsHUD/SettingsGeneralView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Settings/QualitySettingsData.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Settings/Settings.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Settings/SettingsControllers/QualitySettingsController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
  unity-client/Assets/Scripts/MainScripts/Debugging/Performance/PerformanceController.asmdef
  unity-client/Assets/Scripts/MainScripts/Debugging/Performance/PerformanceMetricsController.cs
  unity-client/ProjectSettings/QualitySettings.asset
  unity-client/ProjectSettings/UnityConnectSettings.asset
Labels: ready for review

#1674 chore: controlsHUD updated
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ControlsHUD/Resources/ControlsHUD.prefab
  unity-client/Assets/Textures/UI/BackpackOutlineIcon.png
  unity-client/Assets/Textures/UI/BackpackOutlineIcon.png.meta
  unity-client/Assets/Textures/UI/MouseLocked.png
  unity-client/Assets/Textures/UI/TexturesUI.spriteatlas
Labels: ready for review

#1679 fix: loading on wallet selector
  website/src/components/auth/EthLogin.tsx
  website/src/components/auth/wallet/WalletSelector.tsx
Labels: ready for review

#1673 chore: mapchunk hiccup fix
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/MapChunk.cs
Labels: ready for review

#1686 chore: SettingsHUD grid fixed
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsHUD/Resources/SettingsHUD.prefab
Labels: ready for review

#1694 fix: remove duplicated component from MainTest scene
  unity-client/Assets/Scenes/Test/MainTest.unity
Labels: ready for review

#1666 feat: set HQ images for static picture frames on demand
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTShapeConfig.asset
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTShapeConfig.asset.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTShapeConfig.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTShapeConfig.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTShapeHQImageHandler.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTShapeHQImageHandler.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTShapeLoaderController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/Prefabs/NFTShapeLoader.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Textures/WrappedTextureAsset/WrappedTextureAsset.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Helpers/NFTHelper/NFTMarkets/OpenSea.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Helpers/NFTHelper/Types.cs
Labels: ready for review

#1685 fix: video player reset
  kernel/packages/decentraland-ecs/src/decentraland/Components.ts
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Video/DCLVideoTexture.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Video/Plugins/WebVideoPlayer.jslib
Labels: ready for review

#1699 fix: initial profile fetch issue
  kernel/packages/shared/profiles/sagas.ts
Labels: ready for review

#1691 feat: add name component
  unity-client/Assets/Scripts/MainScripts/DCL/Components/BuilderInWorld.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Components/BuilderInWorld/DCLName.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/BuilderInWorld/DCLName.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/ParcelScene.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Models/Protocol/Protocol.cs
Labels: ready for review

#1709 fix: unsubscribe autoquality controller listeners
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Settings/SettingsControllers/AutoQualitySettingsController.cs
Labels: ready for review

#1714 fix: accessories typo on avatar editor
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Resources/AvatarEditorHUD.prefab
Labels: ready for review

#1715 feat: adds Dapper wallet
  kernel/packages/shared/ethereum/ProviderType.ts
  kernel/packages/shared/ethereum/Web3Connector.ts
  kernel/packages/shared/ethereum/connector/ConnectorFactory.ts
  kernel/packages/shared/ethereum/connector/DapperConnector.ts
  website/src/components/auth/LoginContainer.tsx
Labels: ready for review

#1718 fix: ui atlas issues
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExpressionsHUD/Textures/AvatarExpressions.spriteatlas
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Resources/Taskbar.prefab
  unity-client/Assets/Textures/UI/Cursor.png
  unity-client/Assets/Textures/UI/Cursor.png.meta
  unity-client/Assets/Textures/UI/CursorInteractive.png
  unity-client/Assets/Textures/UI/CursorInteractive.png.meta
  unity-client/Assets/Textures/UI/TexturesUI.spriteatlas
  unity-client/Assets/Textures/UI/WhitePixel.png
  unity-client/Assets/Textures/UI/WhitePixel.png.meta
  unity-client/ProjectSettings/EditorSettings.asset
Labels: ready for review

#1716 chore: black overlay background added
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WelcomeHUD/Resources/WelcomeHUD.prefab
Labels: ready for review

#1711 refactor: separate builder in world favorites and quick bar functionality
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Catalog/FavoritesController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Catalog/FavoritesController.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Catalog/QuickBarController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Catalog/QuickBarController.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Catalog/QuickBarSlot.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Catalog/QuickBarSlot.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Catalog/QuickBarView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Catalog/QuickBarView.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Catalog/SceneObjectCatalog.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/BuilderMode/Catalog/SceneObjectCatalogController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/BuildModeHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/BuildModeHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/BuildModeHUD/Resources/BuildModeHUD.prefab
Labels: ready for review

#1721 refactor: move small systems to environment
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/DCLCharacterController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/DCLCharacterPosition.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/Environment.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/ParcelScene.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/SceneController.cs
Labels: ready for review

#1717 fix: cache and dispose gifs properly
  kernel/packages/gif-processor/processor.ts
  kernel/packages/gif-processor/types.ts
  kernel/packages/gif-processor/worker.ts
  kernel/packages/shared/types.ts
  kernel/packages/unity-interface/BrowserInterface.ts
  kernel/packages/unity-interface/UnityInterface.ts
  kernel/packages/unity-interface/kernelConfigForRenderer.ts
  unity-client/Assets/Scripts/MainScripts/DCL/Bridges/GIFProcessingBridge/GIFCache.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Bridges/GIFProcessingBridge/GIFCache.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Bridges/GIFProcessingBridge/GIFProcessingBridge.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Bridges/GIFProcessingBridge/GIFProcessingBridge.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTShapeLoaderController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Textures/WrappedTextureAsset/WrappedTextureAsset.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Gif/Asset_Gif.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Gif/Asset_Gif.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NFTPromptHUD/NFTPromptHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/KernelConfiguration/KernelConfig.cs
  unity-client/Assets/Scripts/MainScripts/DCL/KernelConfiguration/KernelConfigModel.cs
  unity-client/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
Labels: ready for review

#1726 fix: generated meshes on GLTF import were not optimized
  unity-client/Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs
Labels: ready for review

#1725 fix: loading message with two lines
  website/src/components/loading/LoadingContainer.stories.tsx
  website/src/components/loading/LoadingMessage.tsx
Labels: ready for review

#1719 refactor: move ParcelScenesCleaner to environment
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/MemoryManager/MemoryManager.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/Environment.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/ParcelScene.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/ParcelScenesCleaner.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/SceneBoundariesController/Tests/SBC_Asserts.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/SceneBoundariesController/Tests/SceneBoundariesCheckerTests_DebugMode.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/SceneController.cs
Labels: ready for review

#1713 feat: integrate stateful scenes with content servers
  kernel/package-lock.json
  kernel/package.json
  kernel/packages/scene-system/stateful-scene/RendererStatefulActor.ts
  kernel/packages/scene-system/stateful-scene/SceneStateDefinition.ts
  kernel/packages/scene-system/stateful-scene/SceneStateDefinitionSerializer.ts
  kernel/packages/scene-system/stateful.scene.system.ts
  kernel/packages/shared/apis/SceneStateStorageController.ts
  kernel/packages/shared/apis/SceneStateStorageController/AssetManager.ts
  kernel/packages/shared/apis/SceneStateStorageController/SceneStateDefinitionCodeGenerator.ts
  kernel/packages/shared/apis/SceneStateStorageController/SceneStateStorageController.ts
  kernel/packages/shared/apis/SceneStateStorageController/StorableSceneStateTranslation.ts
  kernel/packages/shared/apis/SceneStateStorageController/types.ts
  kernel/packages/shared/apis/index.ts
  kernel/packages/shared/world/StatefulWorker.ts
Labels: ready for review

#1616 chore: adjust mouse sensitivity
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Camera/Resources/CameraController.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Settings/SettingsControllers/GeneralSettingsController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Settings/SettingsControllers/Tests/GeneralSettingsShould.cs
Labels: ready for review

#1727 feat: set HQ images for gif picture frames on demand
  kernel/packages/gif-processor/processor.ts
  kernel/packages/gif-processor/worker.ts
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTShapeAssetsType.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTShapeAssetsType.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTShapeConfig.asset
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTShapeConfig.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTShapeHQImageHandler.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTShapeLoaderController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Textures/WrappedTextureAsset/WrappedTextureAsset.cs
Labels: ready for review
