Repository decentraland/explorer, pull requests merged in 2020-03, with the labels that each got.

#673 fix: builder scene not starting due to an exception when calling stopTeleportAnimation
  kernel/packages/unity-interface/dcl.ts
Labels: ready for review

#679 fix: builder - entities can't be selected after returning from preview
  unity-client/Assets/Builder/Scripts/DCLBuilderObjectSelector.cs
Labels: ready for review

#678 feat: new survey behaviour
  kernel/packages/unity-interface/dcl.ts
Labels: merge me!

#680 fix: builder - apply custom quality settings for builder
  unity-client/Assets/Builder/Scripts/Builder.asmdef
  unity-client/Assets/Builder/Scripts/DCLBuilderBridge.cs
Labels: ready for review

#696 fix: null exception when removing a entity that was showing a pointer event hover
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/PointerEventsController.cs
Labels: ready for review

#648 chore: enable scene boundaries check
  kernel/public/test-scenes/0.90.scene-boundaries/game.ts
  unity-client/Assets/Builder/Scripts/DCLBuilderBridge.cs
  unity-client/Assets/Builder/Scripts/DCLBuilderEntity.cs
  unity-client/Assets/Builder/Scripts/DCLBuilderObjectSelector.cs
  unity-client/Assets/Resources/Prefabs/SceneController.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Components/UUIDComponent/Tests/UUIDComponentTests.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Tests.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/PhysicsCast/Tests/PhysicsCastTest.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MessagingControllersManager.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/ParcelScene.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/SceneBoundariesController/SceneBoundariesChecker.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/SceneBoundariesController/SceneBoundariesDebugModeChecker.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/SceneBoundariesController/Tests/SBC_Asserts.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/SceneBoundariesController/Tests/SceneBoundariesCheckerTests.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/SceneBoundariesController/Tests/SceneBoundariesCheckerTests_DebugMode.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/SceneController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/SceneMetricsController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Helpers/Utils/Utils.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Models/DecentralandEntity.cs
Labels: ready for review

#694 fix: faster pool cleanup + blocker issues
  unity-client/Assets/Batch/AssetBundleBuilderUtils.cs
  unity-client/Assets/Batch/AssetBundleMenuItems.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/PoolManager/Pool.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/PoolManager/PoolManager.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/PoolManager/Tests/PoolManagerTests.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/BlockerHandler.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/ParcelScene.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/ParcelScenesCleaner.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/Tests/BlockerHandlerShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/Tests/BlockerHandlerShould.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Helpers/Utils/Utils.cs
Labels: ready for review

#698 fix: blocking promises hiccup issue
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/LoadWrapper/LoadWrapper_GLTF.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/LoadWrapper/RendereableAssetLoadHelper.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB/AssetPromise_AB.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB/Tests/BlockedAndMasterPromisesShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB_GameObject/Tests/BlockedAndMasterPromisesShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Common/AssetPromise.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Common/AssetPromiseKeeper.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Common/Mock/Tests/BlockedAndMasterPromisesShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Common/Mock/Tests/PromiseKeeperShouldBehaveCorrectlyWhen.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTF/Tests/BlockedAndMasterPromisesShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Tests.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/RenderingController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/ParcelScene.cs
Labels: ready for review

#703 fix: reenabling Ethereum wallet connection in preview mode
  kernel/packages/entryPoints/preview.ts
  kernel/packages/entryPoints/unity.ts
  kernel/packages/scene-system/scene.system.ts
  kernel/packages/shared/apis/EthereumController.ts
  kernel/packages/shared/index.ts
  kernel/packages/shared/types.ts
  kernel/packages/unity-interface/dcl.ts
  kernel/static/preview.html
Labels: ready for review

#702 fix: builder - dragging entity when trying to rotate camera
  unity-client/Assets/Builder/Scripts/DCLBuilderObjectDragger.cs
  unity-client/Assets/Builder/Scripts/DCLBuilderObjectSelector.cs
Labels: ready for review

#733 revert: "feat: Updated peer library to be optimized by position (#729)" (commit 288dd83)
  kernel/package-lock.json
  kernel/package.json
  kernel/packages/shared/comms/index.ts
  kernel/packages/shared/comms/v2/LighthouseWorldInstanceConnection.ts
Labels: do not merge

#732 fix: blocking promises race condition lock issue
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/LoadWrapper/LoadWrapper_GLTF.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/LoadWrapper/RendereableAssetLoadHelper.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB/AssetPromise_AB.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB/Tests/BlockedAndMasterPromisesShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB_GameObject/AssetPromise_AB_GameObject.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB_GameObject/Tests/BlockedAndMasterPromisesShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Common/AssetPromise.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Common/AssetPromiseKeeper.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Common/Mock/Tests/BlockedAndMasterPromisesShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Common/Mock/Tests/PromiseKeeperShouldBehaveCorrectlyWhen.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTF/Tests/BlockedAndMasterPromisesShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Tests.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/PlayerInfoCardHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/RenderingController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/ParcelScene.cs
Labels: merge me!, ready for review

#731 chore: avatar cursor interaction feedback
  unity-client/Assets/Resources/ScriptableObjects/PlayerInfoCardVisibleState.asset
  unity-client/Assets/Resources/ScriptableObjects/PlayerInfoCardVisibleState.asset.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Components/UUIDComponent/AvatarOnPointerDown.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/UUIDComponent/AvatarOnPointerDown.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Components/UUIDComponent/OnPointerDown.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/UUIDComponent/OnPointerEvent.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/UUIDComponent/OnPointerEventColliders.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/PlayerInfoCardHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/PointerEventsController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/SceneBoundariesController/SceneBoundariesChecker.cs
  unity-client/Assets/Scripts/MainScripts/DCL/ScriptableObject/BooleanVariable.cs
  unity-client/Assets/Scripts/MainScripts/DCL/ScriptableObject/BooleanVariable.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/ScriptableObject/CommonScriptableObjects.cs
Labels: merge me!, ready for review

#743 feat: message to request scenes info around a parcel
  kernel/packages/decentraland-ecs/src/decentraland/Types.ts
  kernel/packages/shared/atlas/actions.ts
  kernel/packages/shared/atlas/sagas.ts
  kernel/packages/shared/atlas/types.ts
  kernel/packages/unity-interface/dcl.ts
  unity-client/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
Labels: ready for review

#728 feat: chunk-based map rendering
  unity-client/Assets/Resources/Prefabs/CharacterController.prefab
  unity-client/Assets/Resources/ScriptableObjects/PlayerWorldPosition.asset
  unity-client/Assets/Resources/ScriptableObjects/PlayerWorldPosition.asset.meta
  unity-client/Assets/Scenes/InitialScene.unity
  unity-client/Assets/Scenes/Test/MainTest.unity
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/DCLCharacterController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/DCLCharacterPosition.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Minimap/MinimapHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Minimap/MinimapHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Minimap/RelativeScale.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Minimap/Resources/MinimapHUD.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/MapAtlas.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/MapAtlas.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/MapChunk.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/MapChunk.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/MapRenderer.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/MapRenderer.asmdef.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/MapRenderer.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/MapRenderer.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/MapUtils.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/MapUtils.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/MinimapMetadata.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/MinimapMetadata.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/MinimapMetadataController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/MinimapMetadataController.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/Resources.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/Resources/Map Chunk.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/Resources/Map Chunk.prefab.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/Resources/Map Renderer.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/Resources/Map Renderer.prefab.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/Tests.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/Tests/MapChunk_Mock.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/Tests/MapChunk_Mock.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/Tests/MapRendererShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/Tests/MapRendererShould.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/Tests/Resources.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/Tests/Resources/Map Chunk Mock.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/Tests/Resources/Map Chunk Mock.prefab.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/Tests/Tests.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/Tests/Tests.asmdef.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Minimap/MinimapCamera.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Minimap/MinimapParcelsView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Minimap/Resources/Minimap.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Minimap/Resources/ParcelMinimapIcon.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Minimap/Test/MinimapTest.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Helpers/Utils/Utils.cs
  unity-client/Assets/Scripts/MainScripts/DCL/ScriptableObject/CommonScriptableObjects.cs
  unity-client/Assets/Textures/MinimapCamera.renderTexture
Labels: ready for review

#749 fix: museum district artifact
  unity-client/Assets/Shaders/MaterialTransition/LWRP/LitInput.hlsl
Labels: ready for review

#753 feat: scene info integration for nav. map
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Minimap/MinimapHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/MapRenderer.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/MinimapMetadata.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/MinimapMetadataController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Minimap.meta
Labels: ready for review

#774 chore: avoid external URL texture forced lowercase
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Textures/DCLTexture.cs
Labels: ready for review

#770 fix: chat accumulated messages performance
  kernel/packages/ui/avatar/chatWindow.ts
Labels: ready for review

#776 feat: AudioStream component
  kernel/packages/decentraland-ecs/src/decentraland/Audio.ts
  kernel/packages/decentraland-ecs/src/decentraland/Components.ts
  kernel/packages/unity-interface/dcl.ts
  kernel/public/test-scenes/0.21.audio-streaming/game.ts
  kernel/public/test-scenes/0.21.audio-streaming/scene.json
  kernel/public/test-scenes/0.21.audio-streaming/tsconfig.json
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Audio/DCLAudioStream.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Audio/DCLAudioStream.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Audio/DCLAudioStream.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Audio/DCLAudioStream.prefab.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Factory/DCLComponentFactory.asset
  unity-client/Assets/Scripts/MainScripts/DCL/Models/Protocol.cs
  unity-client/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
Labels: ready for review

#779 fix: set currentSceneId to null if player is not inside any scene
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Audio/DCLAudioStream.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Minimap/MinimapHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationHUD/Notification.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/SceneController.cs
Labels: ready for review

#780 chore: add navmap production environment toggle
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/NavmapView.cs
Labels: ready for review

#777 feat: add raise-hand avatar expression
  unity-client/Assets/Prefabs/Player.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/Animations/Female/F_RaiseHand.anim
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/Animations/Female/F_RaiseHand.anim.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/Animations/FemaleAnimations.asset
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/Animations/Male/M_RaiseHand.anim
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/Animations/Male/M_RaiseHand.anim.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/Animations/MaleAnimations.asset
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExpressionsHUD/Animations/ButtonAnimation.controller
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExpressionsHUD/Animations/ButtonAnimation.controller.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExpressionsHUD/Animations/RobotDanceButton.controller
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExpressionsHUD/Animations/WaveHandButton.controller
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExpressionsHUD/Resources/ExpressionsHUD.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExpressionsHUD/Textures/FistPump.png
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExpressionsHUD/Textures/RaiseHandIcon.png
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExpressionsHUD/Textures/RaiseHandIcon.png.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExpressionsHUD/Textures/RobotDance.png
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExpressionsHUD/Textures/WaveHand.png
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/InputController/InputController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/InputController/Resources/Expression_RaiseHand.asset
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/InputController/Resources/Expression_RaiseHand.asset.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/PlayerAvatarController/ExpressionsHotKeyController.cs
Labels: ready for review
