Repository decentraland/explorer, pull requests merged in 2020-05, with the labels that each got.

#863 fix: missing dependency (sha3) on package.json
  kernel/package-lock.json
  kernel/package.json
Labels: ready for review

#862 fix: AudioStream and VideoTexture volume settings
  kernel/public/test-scenes/0.21.audio-streaming/game.ts
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Audio/DCLAudioStream.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Video/DCLVideoTexture.cs
  unity-client/Assets/Scripts/MainScripts/MainScripts.asmdef
Labels: ready for review

#860 feat: font support
  kernel/packages/decentraland-ecs/src/decentraland/Components.ts
  kernel/packages/decentraland-ecs/src/decentraland/UIShapes.ts
  kernel/public/test-scenes/0.24.fonts/game.ts
  kernel/public/test-scenes/0.24.fonts/scene.json
  kernel/public/test-scenes/0.24.fonts/tsconfig.json
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Font.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Font/DCLFont.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Font/DCLFont.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Font/Tests.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Font/Tests/FontTests.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Font/Tests/FontTests.asmdef.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Font/Tests/FontTests.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Font/Tests/FontTests.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Components/TextShape/TextShape.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/UI/UIInputText/UIInputText.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/UI/UIText/UIText.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/ParcelScene.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Models/Protocol.cs
Labels: ready for review

#864 feat: open external url from sdk
  kernel/packages/decentraland-ecs/src/decentraland/Types.ts
  kernel/packages/decentraland-ecs/src/ecs/helpers.ts
  kernel/packages/entryPoints/preview.ts
  kernel/packages/entryPoints/unity.ts
  kernel/packages/scene-system/scene.system.ts
  kernel/packages/shared/proto/engineinterface.proto
  kernel/packages/shared/proto/engineinterface_pb.d.ts
  kernel/packages/shared/proto/engineinterface_pb.js
  kernel/packages/shared/types.ts
  kernel/packages/unity-interface/dcl.ts
  kernel/public/test-scenes/0.25.openExternalUrl/game.ts
  kernel/public/test-scenes/0.25.openExternalUrl/scene.json
  kernel/public/test-scenes/0.25.openExternalUrl/tsconfig.json
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExternalUrlPromptHUD.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExternalUrlPromptHUD/AssemblyInfo.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExternalUrlPromptHUD/AssemblyInfo.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExternalUrlPromptHUD/ExternalUrlPromptHUD.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExternalUrlPromptHUD/ExternalUrlPromptHUD.asmdef.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExternalUrlPromptHUD/ExternalUrlPromptHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExternalUrlPromptHUD/ExternalUrlPromptHUDController.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExternalUrlPromptHUD/ExternalUrlPromptView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExternalUrlPromptHUD/ExternalUrlPromptView.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExternalUrlPromptHUD/Resources.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExternalUrlPromptHUD/Resources/ExternalUrlPromptHUD.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExternalUrlPromptHUD/Resources/ExternalUrlPromptHUD.prefab.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExternalUrlPromptHUD/Test.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExternalUrlPromptHUD/Test/ExternalUrlPromptHUDTest.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExternalUrlPromptHUD/Test/ExternalUrlPromptHUDTest.asmdef.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExternalUrlPromptHUD/Test/ExternalUrlPromptHUDTest.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExternalUrlPromptHUD/Test/ExternalUrlPromptHUDTest.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUD.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MessageDecoder.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/MessagingBus.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/SceneController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/WebInterface/Engineinterface.cs
  unity-client/Assets/Textures/UI/ContainerRadius12.png
  unity-client/Assets/Textures/UI/ContainerRadius12.png.meta
  unity-client/Assets/Textures/UI/ContainerRadius6.png
  unity-client/Assets/Textures/UI/ContainerRadius6.png.meta
  unity-client/Assets/Textures/UI/ContainerRadius8.png
  unity-client/Assets/Textures/UI/ContainerRadius8.png.meta
  unity-client/Assets/Textures/UI/HeaderExternalLink.png
  unity-client/Assets/Textures/UI/HeaderExternalLink.png.meta
  unity-client/Assets/Textures/UI/ToggleCheckOff.png
  unity-client/Assets/Textures/UI/ToggleCheckOff.png.meta
  unity-client/Assets/Textures/UI/ToggleCheckOn.png
  unity-client/Assets/Textures/UI/ToggleCheckOn.png.meta
Labels: merge me!, ready for review

#888 fix: add LiberationSans to fonts enum
  kernel/packages/decentraland-ecs/src/decentraland/Components.ts
Labels: ready for review

#886 fix: handle video texture resizing
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Video/Plugins/WebVideoPlayer.cs
Labels: ready for review

#867 fix: increased video volume area
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Video/DCLVideoTexture.cs
Labels: ready for review

#889 fix: friends hud player unblocking
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/Tests/CharacterControllerTests.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/FriendsHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/PlayerInfoCardHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/MaterialTransitionController/Tests/MaterialTransitionControllerTests.cs
  unity-client/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
Labels: ready for review

#885 feat: chat persistent whisper and reply
  unity-client/Assets/Scenes/InitialScene.unity
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Tests.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUD.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Resources/World Chat Window.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/WorldChatWindowHUDShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowHUD.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowHUDView.cs
Labels: ready for review

#893 fix: openExternalUrl pointerEvent check
  kernel/packages/scene-system/scene.system.ts
Labels: ready for review

#892 fix: pressing ESC key send chat messages when it shouldn't
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatEntry.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/Tests/ChatHUDShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Resources/World Chat Window.prefab
Labels: ready for review

#878 feat: chat new preview mode
  kernel/packages/entryPoints/unity.ts
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatEntry.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/Resources/Chat Entry.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/Tests/ChatHUDShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Resources/Taskbar.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/TaskbarHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/TaskbarHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Tests/TaskbarHUDShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/WorldChatWindowHUDShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Helpers/Utils/RectTransformExtensions.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Helpers/Utils/RectTransformExtensions.cs.meta
Labels: ready for review

#899 fix: openExternalURL popup
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExternalUrlPromptHUD/Resources/ExternalUrlPromptHUD.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
Labels: ready for review

#902 chore: hide friend status in player info card
  kernel/packages/shared/chat/private.ts
  kernel/packages/shared/chat/sagas.ts
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/FriendsController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/PlayerInfoCardHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/Resources/PlayerInfoCardHUD.prefab
Labels: wip

#906 fix: openExternalURL popup typo
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExternalUrlPromptHUD/Resources/ExternalUrlPromptHUD.prefab
Labels: ready for review

#903 fix: avatar emotes popup
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExpressionsHUD/ExpressionsHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExpressionsHUD/ExpressionsHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExpressionsHUD/Resources/ExpressionsHUD.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/InputController/InputController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/UserProfile/UserProfile.cs
Labels: ready for review

#911 chore: disable CI flaky tests temporarily
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/Tests/CharacterControllerTests.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/MaterialTransitionController/Tests/MaterialTransitionControllerTests.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/SceneBoundariesController/Tests/SceneBoundariesCheckerTests.cs
  unity-client/Assets/Scripts/Tests/CursorControllerTests/CursorControllerTests.cs
Labels: ready for review

#910 fix: flip picture frame image
  .circleci/config.yml
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/PictureFrame.fbx
Labels: ready for review

#912 fix: new chat mini fixes
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatEntry.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/PrivateChatWindowHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/PrivateChatWindowHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/Tests/PrivateChatWindowHUDShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Resources/World Chat Window.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Helpers/Utils/Utils.cs
Labels: ready for review

#916 feat: VideoTexture support video from scene's file
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Video/DCLVideoClip.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Video/DCLVideoTexture.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Video/Plugins/WebVideoPlayer.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Video/Plugins/WebVideoPlayer.jslib
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Video/Tests/VideoTests.cs
Labels: ready for review

#922 fix: open urls from inside the world
  kernel/packages/unity-interface/dcl.ts
Labels: ready for review

#897 feat: Friend list sorting + conversation badges
  unity-client/Assets/Resources/ScriptableObjects/LastReadChatMessages.asset
  unity-client/Assets/Resources/ScriptableObjects/LastReadChatMessages.asset.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/FriendsHUD.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Resources/FriendEntry.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Resources/FriendsHUD.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/Entries/FriendEntry.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/FriendsHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/Tabs/FriendsTabView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/Tabs/FriendsTabViewBase.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationBadge/NotificationBadge.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationBadge/Resources.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationBadge/Resources/UnreadNotificationBadge.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationBadge/Resources/UnreadNotificationBadge.prefab.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationBadge/Tests.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationBadge/Tests/NotificationBadgeTests.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationBadge/Tests/NotificationBadgeTests.asmdef.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationBadge/Tests/UnreadNotificationBadgeShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationBadge/Tests/UnreadNotificationBadgeShould.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationBadge/UnreadNotificationBadge.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationBadge/UnreadNotificationBadge.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/PrivateChatWindowHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/ScriptableObject/CommonScriptableObjects.cs
  unity-client/Assets/Scripts/MainScripts/DCL/ScriptableObject/ReadMessagesDictionary.cs
  unity-client/Assets/Scripts/MainScripts/DCL/ScriptableObject/ReadMessagesDictionary.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/ScriptableObject/Variables/BaseDictionary.cs
Labels: ready for review

#914 style: private chat window
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/FriendsController/FriendsController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatEntry.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Tests/FriendsHUDControllerShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/PrivateChatEntryBackgroundFitter.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/PrivateChatEntryBackgroundFitter.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/PrivateChatHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/PrivateChatHUDView.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/PrivateChatWindowHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/PrivateChatWindowHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/Resources/ChatEntryReceived.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/Resources/ChatEntryReceived.prefab.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/Resources/ChatEntrySent.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/Resources/ChatEntrySent.prefab.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/Resources/PrivateChatWindow.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/Tests/PrivateChatWindowHUDShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/Tests/PrivateChatWindowHUDTests.asmdef
  unity-client/Assets/Textures/UI/BackButton.png
  unity-client/Assets/Textures/UI/BackButton.png.meta
  unity-client/Assets/Textures/UI/PatternPC.png
  unity-client/Assets/Textures/UI/PatternPC.png.meta
Labels: ready for review

#921 feat: using content v3 to retrieve scenes
  kernel/packages/decentraland-loader/lifecycle/controllers/download.ts
  kernel/packages/decentraland-loader/lifecycle/controllers/scene.ts
Labels: ready for review

#920 fix: handling case where user has not yet logged in
  kernel/package-lock.json
  kernel/package.json
  kernel/packages/shared/chat/private.ts
Labels: ready for review

#926 style: taskbar windows
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Resources/FriendEntry.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Resources/FriendRequestEntry.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Resources/FriendsHUD.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Resources/NotificationBadge_FriendsRequestTab.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/Resources/ChatEntryReceived.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/Resources/ChatEntrySent.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/Resources/PrivateChatWindow.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Resources/ChatHead.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Resources/Taskbar.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ButtonAnimations/Highlighted.anim
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/ButtonAnimations/Selected.anim
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Resources/World Chat Window.prefab
  unity-client/Assets/Textures/UI/MessageReceived.png
  unity-client/Assets/Textures/UI/MessageReceived.png.meta
  unity-client/Assets/Textures/UI/MessageSent.png
  unity-client/Assets/Textures/UI/MessageSent.png.meta
  unity-client/Assets/Textures/UI/TaskbarCheckmark.png
Labels: ready for review

#919 feat: VideoTexture new features added
  kernel/packages/decentraland-ecs/src/decentraland/Components.ts
  kernel/public/test-scenes/0.23.video/game.ts
  kernel/public/test-scenes/0.23.video/video1.mp4
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Video/DCLVideoTexture.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Video/Plugins/WebVideoPlayer.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Video/Plugins/WebVideoPlayer.jslib
Labels: ready for review

#925 chore: open private chat with global message
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Tests.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatEntry.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/Resources/Chat Entry.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/PrivateChatWindowHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowHUDController.cs
Labels: ready for review

#923 test: Unread Notification Badge
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationBadge/Tests/NotificationBadgeTests.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationBadge/Tests/UnreadNotificationBadgeShould.cs
Labels: ready for review

#933 chore: new reflection texture
  unity-client/Assets/Textures/CubemapPlaza.jpg
Labels: ready for review

#935 fix: send private empty messages to kernel
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/Tests/ChatHUDShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/PrivateChatWindowHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/PrivateChatWindowHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/Tests/PrivateChatWindowHUDShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/Tests/WorldChatWindowHUDShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowHUDView.cs
Labels: ready for review

#949 fix: add missing rare item in factories
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AirdroppingHUD/Resources/CollectibleFactory.asset
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Data/ItemToggleFactory.asset
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/Data/PlayerInfoCollectiblesFactory.asset
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PlayerInfoCardHUD/Resources/PlayerInfoCollectible_Rare.prefab
Labels: ready for review

#948 fix: VideoTexture handle video stream source not found error
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Video/DCLVideoTexture.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Video/Plugins/WebVideoPlayer.jslib
Labels: ready for review

#956 fix: Conflicts pressing RETURN key on AddFriends window
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/TaskbarHUDController.cs
Labels: ready for review

#957 fix: empty message with whisper
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ChatWidgetHUD/ChatHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/PrivateChatWindow/PrivateChatWindowHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowHUDController.cs
Labels: ready for review

#959 fix: Hide JumpIn button when not receives realm info from a friend
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Resources/FriendsHUD.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/FriendsHUD/Scripts/JumpInButton.cs
Labels: ready for review

#961 fix: world chat input in preview mode
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/NavmapToastView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/WorldChatWindowHUD/WorldChatWindowHUDController.cs
Labels: ready for review
