Repository decentraland/explorer, pull requests merged in 2020-09, with the labels that each got.

#1235 Feat: allows to user save his interests
  kernel/packages/shared/profiles/transformations/processServerProfile.ts
  kernel/packages/shared/profiles/types.ts
  kernel/packages/unity-interface/BrowserInterface.ts
  kernel/test/index.ts
  kernel/test/unit/BrowserInterface.test.tsx
Labels: ready for review

#1234 fix: gifs firefox crash
  kernel/packages/unity-interface/BrowserInterface.ts
  kernel/packages/unity-interface/UnityInterface.ts
  unity-client/Assets/Scripts/MainScripts/DCL/Bridges/GIFProcessingBridge/GIFProcessingBridge.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/Gif/Asset_Gif.cs
Labels: ready for review

#1239 fix: renderer-based animation culling reverted temporarily
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/AssetBundles/AB_GameObject/AssetPromise_AB_GameObject.cs
  unity-client/Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs
Labels: ready for review

#1225 fix: (builder) add support for teleport, nft dialog and external links
  kernel/packages/entryPoints/editor.ts
  unity-client/Assets/Builder/Scripts/Builder.asmdef
  unity-client/Assets/Builder/Scripts/DCLBuilderBridge.cs
Labels: ready for review

#1236 fix: openExternalURL HUD add animator and fixed initial config
  kernel/packages/entryPoints/unity.ts
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExternalUrlPromptHUD/ExternalUrlPromptHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExternalUrlPromptHUD/ExternalUrlPromptView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExternalUrlPromptHUD/Resources/ExternalUrlPromptHUD.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExternalUrlPromptHUD/Test/ExternalUrlPromptHUDTest.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExternalUrlPromptHUD/Test/ExternalUrlPromptHUDTest.cs
Labels: ready for review

#1244 fix: load avatars when exporting a scene
  kernel/static/default-profile/basecatalog.json
Labels: ready for review

#1242 fix: (builder) drag, drop and clicks
  kernel/packages/unity-interface/UnityInterface.ts
  kernel/packages/unity-interface/dcl.ts
  unity-client/Assets/Builder/Scripts/DCLBuilderEntity.cs
  unity-client/Assets/Builder/Scripts/DCLBuilderObjectSelector.cs
Labels: ready for review

#1246 fix: upload visual test artifacts to CircleCi
  .circleci/config.yml
Labels: ready for review

#1231 fix: upside down nftshapes
  README.md
  unity-client/Assets/Resources/TestTexture.png
  unity-client/Assets/Resources/TestTexture.png.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTShapeLoaderController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/Resources/NFTShapeLoader_Classic.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/Tests/LoadableShapesTests.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/Tests/NFTShapeVisualTests.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/Tests/NFTShapeVisualTests.cs.meta
  unity-client/Assets/Scripts/Tests/VisualTests/UIVisualTestsBase.cs
  unity-client/Assets/Scripts/Tests/VisualTests/VisualTestsBase.cs
  unity-client/TestResources/VisualTests/BaselineImages/NFTShapeVisualTest1_0.png
  unity-client/TestResources/VisualTests/BaselineImages/NFTShapeVisualTest2_0.png
  unity-client/TestResources/VisualTests/BaselineImages/NFTShapeVisualTest3_0.png
  unity-client/TestResources/VisualTests/BaselineImages/NFTShapeVisualTest4_0.png
Labels: ready for review

#1248 fix: openExternalUrl HUD appearing at preview start
  kernel/packages/entryPoints/preview.ts
Labels: ready for review

#1243 fix: bad avatar wearable error handling with invalid catalog queries
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarRenderer.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/Tests/AvatarRendererShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/Tests/AvatarShape_Helpers.cs
Labels: ready for review

#1211 fix: texture name collision in gltf importer
  unity-client/Assets/Batch/AssetBundleBuilder.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/Tests/GLTFImporterTests.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/AssetManager/GLTF/AssetPromise_GLTF.cs
  unity-client/Assets/UnityGLTF/Scripts/Cache/AssetCache.cs
  unity-client/Assets/UnityGLTF/Scripts/Cache/RefCountedTextureData.cs
  unity-client/Assets/UnityGLTF/Scripts/Editor/GLTFImporter.cs
  unity-client/Assets/UnityGLTF/Scripts/GLTFComponent.cs
  unity-client/Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs
  unity-client/Assets/UnityGLTF/Tests/GLTFBenchmark.cs
  unity-client/TestResources/GLTF/Trunk2/MiniTown_TX.png
  unity-client/TestResources/GLTF/Trunk2/Trunk.bin
  unity-client/TestResources/GLTF/Trunk2/Trunk.gltf
Labels: ready for review

#1252 Chore: add catalyst-client to update profile
  kernel/package-lock.json
  kernel/package.json
  kernel/packages/shared/profiles/sagas.ts
Labels: ready for review

#1216 feat: track interface
  kernel/packages/shared/analytics.ts
  kernel/packages/unity-interface/BrowserInterface.ts
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/EmailPromptHUD/EmailPromptHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
Labels: ready for review

#1260 chore: Makefile download renderer of current branch
  kernel/Makefile
Labels: ready for review

#1262 fix: picture frames share frame material
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTShapeLoaderController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTShapeMaterial.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/NFTShapeMaterial.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/Prefabs/NFTShapeLoader_Baroque_Ornament.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/Prefabs/NFTShapeLoader_Blocky.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/Prefabs/NFTShapeLoader_Canvas.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/Prefabs/NFTShapeLoader_Diamond_Ornament.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/Prefabs/NFTShapeLoader_Gold_Carved.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/Prefabs/NFTShapeLoader_Gold_Edges.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/Prefabs/NFTShapeLoader_Gold_Rounded.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/Prefabs/NFTShapeLoader_Gold_Wide.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/Prefabs/NFTShapeLoader_Metal_Medium.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/Prefabs/NFTShapeLoader_Metal_Rounded.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/Prefabs/NFTShapeLoader_Metal_Slim.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/Prefabs/NFTShapeLoader_Metal_Wide.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/Prefabs/NFTShapeLoader_Minimal_Black.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/Prefabs/NFTShapeLoader_Minimal_Grey.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/Prefabs/NFTShapeLoader_Minimal_White.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/Prefabs/NFTShapeLoader_Minimal_Wide.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/Prefabs/NFTShapeLoader_Pins.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/Prefabs/NFTShapeLoader_Tape.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/Prefabs/NFTShapeLoader_Wood_Slim.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/Prefabs/NFTShapeLoader_Wood_Twigs.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/Prefabs/NFTShapeLoader_Wood_Wide.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/NFTShape/Resources/NFTShapeLoader_Classic.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/Tests/NFTShape_Tests.cs
Labels: ready for review

#1264 chore: modifications in HotScenesController test
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HotScenesController/AssemblyInfo.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HotScenesController/AssemblyInfo.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HotScenesController/HotScenesController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HotScenesController/Tests/HotScenesControllerTests.cs
Labels: ready for review

#1257 feat: add MANA HUD
  kernel/packages/config/index.ts
  kernel/packages/entryPoints/unity.ts
  kernel/packages/shared/types.ts
  kernel/packages/unity-interface/BrowserInterface.ts
  kernel/packages/unity-interface/UnityInterface.ts
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Common/ShowHideAnimator/UIHoverTriggerShowHideAnimator.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUD.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ManaHUD.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ManaHUD/AssemblyInfo.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ManaHUD/AssemblyInfo.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ManaHUD/ManaHUD.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ManaHUD/ManaHUD.asmdef.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ManaHUD/ManaHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ManaHUD/ManaHUDController.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ManaHUD/ManaHUDview.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ManaHUD/ManaHUDview.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ManaHUD/Resources.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ManaHUD/Resources/ManaHUD.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ManaHUD/Resources/ManaHUD.prefab.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ManaHUD/Test.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ManaHUD/Test/ManaHUDTest.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ManaHUD/Test/ManaHUDTest.asmdef.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ManaHUD/Test/ManaHUDTest.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ManaHUD/Test/ManaHUDTest.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ManaHUD/Textures.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ManaHUD/Textures/Icon.png
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ManaHUD/Textures/Icon.png.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ManaHUD/Textures/container.png
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ManaHUD/Textures/container.png.meta
  unity-client/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
  unity-client/Assets/Scripts/MainScripts/Debugging/WSS/WSSController.cs
Labels: ready for review

#1271 feat: changes to attachable based on feedback
  kernel/package-lock.json
  kernel/package.json
  kernel/packages/decentraland-ecs/src/ecs/Attachable.ts
  kernel/packages/decentraland-ecs/src/ecs/Engine.ts
  kernel/packages/decentraland-ecs/src/ecs/IEntity.ts
  kernel/public/test-scenes/0.102.attachables/game.ts
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/DCLCharacterController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/FirstPersonCameraEntityReference.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/FirstPersonCameraEntityReference.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/Resources/Prefabs/CharacterController.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/ParcelScene.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/Tests/SceneTests.cs
Labels: ready for review

#1263 fix: explore and navmap scene's thumbnails
  kernel/packages/shared/atlas/sagas.ts
  kernel/packages/shared/selectors.ts
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/ExploreHUD.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Prefabs/HotSceneCellView.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Prefabs/SceneInfoView.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Resources/ExploreHUD.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Scripts/BaseCellView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Scripts/BaseSceneCellView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Scripts/HighlightScenes/SceneInfoView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/NavMap.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Navmap.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/NavmapToastView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Tests/NavmapToastViewShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Textures/PinIcon.png
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Textures/PinIcon.png.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/Resources/Map Renderer.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Helpers/UIHelpers/RawImageFillParent.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Helpers/UIHelpers/RawImageFillParent.cs.meta
  unity-client/Assets/Textures/UI/ScenesContainer.png.meta
  unity-client/Assets/Textures/UI/SelectedParcel.png
Labels: ready for review

#1251 feat: New Taskbar implementation
  kernel/packages/config/index.ts
  kernel/packages/entryPoints/unity.ts
  kernel/packages/shared/types.ts
  kernel/packages/unity-interface/UnityInterface.ts
  kernel/packages/unity-interface/dcl.ts
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Common/ShowHideAnimator/AnimatorDefault/Hide.anim
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Common/ShowHideAnimator/AnimatorDefault/Show.anim
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/AssemblyInfo.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/ExploreHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/ExploreHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Resources/ExploreHUD.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Scripts/Friends/FriendTrackerController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Scripts/Friends/IFriendTrackerHandler.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Scripts/MiniMapData/ExploreMiniMapDataController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Scripts/MiniMapData/IMapDataView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Test/ExploretHUDTest.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUD.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HelpAndSupportHUD.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HelpAndSupportHUD/HelpAndSupportHUD.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HelpAndSupportHUD/HelpAndSupportHUD.asmdef.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HelpAndSupportHUD/HelpAndSupportHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HelpAndSupportHUD/HelpAndSupportHUDController.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HelpAndSupportHUD/HelpAndSupportHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HelpAndSupportHUD/HelpAndSupportHUDView.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HelpAndSupportHUD/Resources.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HelpAndSupportHUD/Resources/HelpAndSupportHUD.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HelpAndSupportHUD/Resources/HelpAndSupportHUD.prefab.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HelpAndSupportHUD/Test.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HelpAndSupportHUD/Test/HelpAndSupportHUDControllerShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HelpAndSupportHUD/Test/HelpAndSupportHUDControllerShould.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HelpAndSupportHUD/Test/HelpAndSupportHUDTests.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HelpAndSupportHUD/Test/HelpAndSupportHUDTests.asmdef.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsHUD/Resources/SettingsHUD.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsHUD/SettingsHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/SettingsHUD/SettingsHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Animations/HideTaskbar.anim
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Animations/HideTaskbar.anim.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Animations/ShowTaskbar.anim
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Animations/ShowTaskbar.anim.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Animations/TaskbarAnimator.controller
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Animations/TaskbarAnimator.controller.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Resources/Taskbar.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/TaskbarHUD.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/TaskbarHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/TaskbarHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/TaskbarMoreMenu.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/TaskbarMoreMenu.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Tests/TaskbarHUDShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/TaskbarHUD/Tests/TaskbarHUDTests.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/PoolManager.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Interfaces.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Models.meta
  unity-client/Assets/Scripts/MainScripts/Debugging/WSS/WSSController.cs
Labels: ready for review

#1272 chore: AvatarHUD as legacy
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarHUD/AvatarHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarHUD/AvatarHUDModel.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarHUD/AvatarHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarHUD/Legacy.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarHUD/Legacy/AvatarHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarHUD/Legacy/AvatarHUDController.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarHUD/Legacy/AvatarHUDModel.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarHUD/Legacy/AvatarHUDModel.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarHUD/Legacy/AvatarHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarHUD/Legacy/AvatarHUDView.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarHUD/Resources.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarHUD/Resources/Legacy.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarHUD/Resources/Legacy/AvatarHUD.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarHUD/Resources/Legacy/AvatarHUD.prefab.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarHUD/Tests/Legacy.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarHUD/Tests/Legacy/AvatarHUDTests.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarHUD/Tests/Legacy/AvatarHUDTests.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDController.cs
Labels: ready for review

#1273 chore: refactor to enable custom HUDConfiguration
  kernel/packages/unity-interface/UnityInterface.ts
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Tests/HUDTests.cs
Labels: ready for review

#1265 fix: plane shape not receiving shadows
  unity-client/Assets/Scripts/MainScripts/DCL/Components/ParametrizedShapes/Tests/ParametrizedShapesTests.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Components/ParametrizedShapes/Tests/ParametrizedShapesTests.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/ParametrizedShapes/Tests/PlaneShapeShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/ParametrizedShapes/Tests/PlaneShapeShould.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Components/ParametrizedShapes/Tests/PlaneShapeShould_VisualTests.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/ParametrizedShapes/Tests/PlaneShapeShould_VisualTests.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/MemoryManager/MemoryManager.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Helpers/PrimitiveMeshBuilder.cs
  unity-client/Assets/Scripts/Tests/VisualTests/VisualTestsBase.cs
  unity-client/TestResources/VisualTests/BaselineImages/PlaneShape_ReceiveShadowsCorrectly_0.png
Labels: ready for review

#1253 fix: badly optimized animations related crash
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/Tests/AnimationCurveContainer.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/Tests/AnimationCurveContainer.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/Tests/GLTFImporterTests.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/Tests/Resources.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/Tests/Resources/CurveOptimizedCorrectlyResult.asset
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/Tests/Resources/CurveOptimizedCorrectlyResult.asset.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/Tests/Resources/CurveOptimizedCorrectlySource.asset
  unity-client/Assets/Scripts/MainScripts/DCL/Components/LoadableShapes/Tests/Resources/CurveOptimizedCorrectlySource.asset.meta
  unity-client/Assets/UnityGLTF/Scripts/GLTFSceneImporter.cs
Labels: ready for review

#1280 fix: hidden list for BodyShapeController is not being refreshed properly.
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarRenderer.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/BodyShapeController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/Tests/AvatarRendererShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/Tests/AvatarShape_Helpers.cs
Labels: ready for review

#1223 fix: entites out of boundaries material on remove
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/PoolManager/PoolManager.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/PoolManager/Tests/PoolManagerTests.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/ParcelScene.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/SceneBoundariesController/SceneBoundariesChecker.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/SceneBoundariesController/SceneBoundariesDebugModeChecker.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/SceneBoundariesController/Tests/SceneBoundariesCheckerTests_DebugMode.cs
Labels: ready for review

#1281 release: 2020-09-09
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarRenderer.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/BodyShapeController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/Tests/AvatarRendererShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/Tests/AvatarShape_Helpers.cs
Labels: ready for review

#1279 chore: renamed AvatarHUD to ProfileHUD
  kernel/packages/entryPoints/unity.ts
  kernel/packages/shared/types.ts
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarHUD/AvatarHUD.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Legacy.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Legacy/AvatarHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Legacy/AvatarHUDController.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Legacy/AvatarHUDModel.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Legacy/AvatarHUDModel.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Legacy/AvatarHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Legacy/AvatarHUDView.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ProfileHUD.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ProfileHUD.asmdef.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Resources.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Resources/Legacy.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Resources/Legacy/AvatarHUD.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Resources/Legacy/AvatarHUD.prefab.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Tests.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Tests/Legacy.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Tests/Legacy/AvatarHUDTests.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Tests/Legacy/AvatarHUDTests.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Tests/ProfileHUDTests.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Tests/ProfileHUDTests.asmdef.meta
Labels: ready for review

#1284 Bones in SkinnedMeshRenderer now are commanded by a mock SkinnedMeshR…
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/BodyShapeController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/WearableController.cs
Labels: ready for review

#1288 feat: add animations to explore
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Animations/HotSceneCellViewAnimator.controller
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Animations/HotSceneCellViewAnimator.controller.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Animations/HotSceneCellViewIn.anim
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Animations/HotSceneCellViewIn.anim.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Animations/HotSceneCellViewLoaded.anim
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Animations/HotSceneCellViewLoaded.anim.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Animations/LoadingController.controller
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Animations/LoadingController.controller.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Animations/LoadingLoop.anim
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Animations/LoadingLoop.anim.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/ExploreHUD.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/ExploreHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Prefabs/HotSceneCellView.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Prefabs/Loading.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Prefabs/Loading.prefab.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Resources/ExploreHUD.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Scripts/BaseCellView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Scripts/BaseSceneCellView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Scripts/Handlers.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Scripts/Handlers/AnimationHandler.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Scripts/Handlers/AnimationHandler.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Scripts/Handlers/CrowdHandler.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Scripts/Handlers/CrowdHandler.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Scripts/Handlers/FriendsHandler.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Scripts/Handlers/FriendsHandler.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Scripts/Handlers/MapInfoHandler.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Scripts/Handlers/MapInfoHandler.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Scripts/Handlers/ThumbnailHandler.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Scripts/Handlers/ThumbnailHandler.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Scripts/HighlightScenes/HighlightScenesController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Scripts/HighlightScenes/HotSceneCellView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Scripts/HighlightScenes/SceneInfoView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Scripts/ViewPool.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ExploreHUD/Test/ExploretHUDTest.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/NavMap.prefab
  unity-client/Assets/Textures/UI/Button10.png
  unity-client/Assets/Textures/UI/Button10.png.meta
  unity-client/Assets/Textures/UI/Button12.png
  unity-client/Assets/Textures/UI/Button12.png.meta
  unity-client/Assets/Textures/UI/Button8.png
  unity-client/Assets/Textures/UI/Button8.png.meta
  unity-client/Assets/Textures/UI/CloseButton.png
  unity-client/Assets/Textures/UI/ContainerRadius20.png
  unity-client/Assets/Textures/UI/ContainerRadius20.png.meta
  unity-client/Assets/Textures/UI/ImageIcon.png
  unity-client/Assets/Textures/UI/ImageIcon.png.meta
Labels: ready for review

#1282 chore: decouple navmap from minimap
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Minimap/MinimapHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Minimap/Resources/MinimapHUD.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/NavmapView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Tests/NavmapTests.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Tests/NavmapTests.cs
Labels: ready for review

#1302 fix: added AlphaTexture
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Materials/PBRMaterial.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Materials/Tests/MaterialsTests.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Materials/Tests/PBRMaterialVisualTests.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Materials/Tests/PBRMaterialVisualTests.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Helpers/MaterialHelpers/SRPBatchingHelper/SRPBatchingHelper.cs
  unity-client/Assets/Scripts/Tests/TestHelpers.cs
  unity-client/Assets/Shaders/MaterialTransition/LWRP/Lit.shader
  unity-client/Assets/Shaders/MaterialTransition/LWRP/LitInput.hlsl
  unity-client/TestResources/Images/alphaTexture.png
  unity-client/TestResources/VisualTests/BaselineImages/PBRMaterialVisualTests_AlphaTextureShouldWork_0.png
Labels: ready for review

#1310 fix: navmap toast show default thumbnail
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/NavmapToastView.cs
  unity-client/Assets/Textures/UI/ThumbnailDownloadError.png
Labels: ready for review

#1304 feat: avatar modifier area
  kernel/packages/decentraland-ecs/src/decentraland/Components.ts
  kernel/public/test-scenes/0.103.avatar-modifiers/game.ts
  kernel/public/test-scenes/0.103.avatar-modifiers/scene.json
  unity-client/Assets/Scenes/InitialScene.unity
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarModifiers.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarModifiers/AvatarModifierArea.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarModifiers/AvatarModifierArea.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarModifiers/AvatarModifierArea.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarModifiers/AvatarModifierArea.prefab.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarModifiers/TriggerArea.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarModifiers/TriggerArea.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarModifiers/modifiers.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarModifiers/modifiers/AvatarModifier.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarModifiers/modifiers/AvatarModifier.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarModifiers/modifiers/DisablePassportModifier.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarModifiers/modifiers/DisablePassportModifier.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarModifiers/modifiers/HideAvatarsModifier.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarModifiers/modifiers/HideAvatarsModifier.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarVisibility.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarVisibility.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/Tests/AvatarVisibilityTests.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/Tests/AvatarVisibilityTests.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/Resources/Prefabs/CharacterController.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/PhysicsSyncController/PhysicsSyncController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/PlayerAvatarController/PlayerAvatarController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Factory/DCLComponentFactory.asset
  unity-client/Assets/Scripts/MainScripts/DCL/Models/Protocol/Protocol.cs
  unity-client/ProjectSettings/TagManager.asset
Labels: ready for review

#1293 feat: new avatar hud
  kernel/packages/entryPoints/unity.ts
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/AssemblyInfo.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/AssemblyInfo.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Legacy/AvatarHUDConfiguration.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Legacy/AvatarHUDConfiguration.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ProfileHUD.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ProfileHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ProfileHUDController.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ProfileHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/ProfileHUDView.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Resources/ProfileHUD.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Resources/ProfileHUD.prefab.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Tests/ProfileHUDTests.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Tests/ProfileHUDTests.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Tests/ProfileHUDTests.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Textures.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Textures/ClaimIcon.png
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Textures/ClaimIcon.png.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Textures/CopyIcon.png
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Textures/CopyIcon.png.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Textures/EditIcon.png
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Textures/EditIcon.png.meta
Labels: ready for review

#1317 fix: Remove TutorialController from MainTest scene
  unity-client/Assets/Scenes/Test/MainTest.unity
Labels: ready for review

#1307 fix: shared Primitives on different entities now update them properly.
  unity-client/Assets/Scripts/MainScripts/DCL/Components/ParametrizedShapes/ParametrizedShape.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/ParametrizedShapes/Tests/ParametrizedShapesTests.cs
Labels: ready for review

#1318 fix: set avatar colliders as triggers
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/Resources/Prefabs/CharacterController.prefab
Labels: ready for review

#1277 feat: Global voice chat Experimental Feature
  kernel/Makefile
  kernel/packages/atomicHelpers/RingBuffer.ts
  kernel/packages/atomicHelpers/defer.ts
  kernel/packages/config/index.ts
  kernel/packages/decentraland-ecs/src/decentraland/AvatarShape.ts
  kernel/packages/shared/comms/actions.ts
  kernel/packages/shared/comms/index.ts
  kernel/packages/shared/comms/interface/index.ts
  kernel/packages/shared/comms/interface/types.ts
  kernel/packages/shared/comms/interface/utils.ts
  kernel/packages/shared/comms/peers.ts
  kernel/packages/shared/comms/reducer.ts
  kernel/packages/shared/comms/sagas.ts
  kernel/packages/shared/comms/selectors.ts
  kernel/packages/shared/comms/types.ts
  kernel/packages/shared/comms/v1/brokerWorldInstanceConnection.ts
  kernel/packages/shared/comms/v2/LighthouseWorldInstanceConnection.ts
  kernel/packages/shared/comms/v2/proto/comms.proto
  kernel/packages/shared/comms/v2/proto/comms_pb.d.ts
  kernel/packages/shared/comms/v2/proto/comms_pb.js
  kernel/packages/ui/avatar/avatarSystem.ts
  kernel/packages/unity-interface/BrowserInterface.ts
  kernel/packages/unity-interface/UnityInterface.ts
  kernel/packages/voice-chat-codec/VoiceChatCodecWorkerMain.ts
  kernel/packages/voice-chat-codec/VoiceCommunicator.ts
  kernel/packages/voice-chat-codec/resampler.ts
  kernel/packages/voice-chat-codec/tsconfig.json
  kernel/packages/voice-chat-codec/types.ts
  kernel/packages/voice-chat-codec/worker.ts
  kernel/static/voice-chat-codec/libopus.wasm
  kernel/static/voice-chat-codec/libopus.wasm.js
  kernel/static/voice-chat-codec/worker.js
  kernel/targets/engine/voice-chat-codec.json
  kernel/test/atomicHelpers/RingBuffer.test.ts
  unity-client/Assets/Prefabs/Player.prefab
  unity-client/Assets/Scenes/InitialScene.unity
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarName.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Legacy/AvatarHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Legacy/AvatarHUDView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/ProfileHUD/Resources/Legacy/AvatarHUD.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/InputController/InputController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/InputController/Resources/VoiceChatRecording.asset
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/InputController/Resources/VoiceChatRecording.asset.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/VoiceChat.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/VoiceChat/DCLVoiceChatController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/VoiceChat/DCLVoiceChatController.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Models/AvatarModel/AvatarModel.cs
  unity-client/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
  unity-client/Assets/Scripts/MainScripts/Debugging/WSS/WSSController.cs
  unity-client/Assets/Textures/UI/MicrophoneIcon.png
  unity-client/Assets/Textures/UI/MicrophoneIcon.png.meta
Labels: ready for review

#1323 feat: Integration of AvatarEditorHUD in the Onboarding flow
  kernel/packages/entryPoints/unity.ts
  kernel/packages/shared/ethereum/Web3Connector.ts
  kernel/packages/shared/ethereum/provider.ts
  kernel/packages/shared/profiles/sagas.ts
  kernel/packages/shared/session/authFlow.ts
  kernel/packages/shared/session/sagas.ts
  kernel/packages/unity-interface/BrowserInterface.ts
  kernel/packages/unity-interface/UnityInterface.ts
  kernel/packages/unity-interface/dcl.ts
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/AvatarEditorHUD/Scripts/AvatarEditorHUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Rendering/RenderingController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/WebInterface/Interface.cs
  unity-client/Assets/Scripts/MainScripts/Debugging/WSS/WSSController.cs
  unity-client/Assets/Tutorial/Scripts/Tutorial.asmdef
  unity-client/Assets/Tutorial/Scripts/TutorialController.cs
Labels: wip

#1326 fix: show logs with DEBUG_SCENE_LOG
  kernel/packages/unity-interface/UnityParcelScene.ts
Labels: ready for review

#1330 chore: enable explore hud
  kernel/packages/config/index.ts
  kernel/packages/entryPoints/unity.ts
Labels: ready for review

#1305 feat: map reskin plus animations
  unity-client/Assets/Scenes/InitialScene.unity
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/Minimap/Resources/MinimapHUD.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Animation.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Animation/ToastNavMapController.controller
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Animation/ToastNavMapController.controller.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Animation/ToastNavMapIn.anim
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Animation/ToastNavMapIn.anim.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Animation/ToastNavMapLoaded.anim
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Animation/ToastNavMapLoaded.anim.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/NavMap.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Navmap.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/NavmapToastView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Textures/Button.png
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Textures/Button.png.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Textures/CloseButton.png
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Textures/CloseButton.png.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Textures/CollapsablePanel.png
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Textures/Compass.png.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Textures/Ellipse.png
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Textures/Ellipse.png.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Textures/PlaceHolderImg.png
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Textures/PlaceHolderImg.png.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Textures/PoiIcon.png
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Textures/PoiIcon.png.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Textures/Rectangle.png
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Textures/Rectangle.png.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Textures/RectangleShadow.png
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Textures/RectangleShadow.png.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Textures/WhiteGradientPanel.png
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Textures/WhiteGradientPanel.png.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/Resources/Map Renderer.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/MapRenderer/Resources/Map Scene Icon POI.prefab
  unity-client/Assets/Textures/UI/Compass.png
  unity-client/Assets/Textures/UI/Compass.png.meta
  unity-client/Assets/Textures/UI/PoiIcon.png
  unity-client/Assets/Textures/UI/PoiIcon.png.meta
  unity-client/Assets/Textures/UI/Pointer.png
Labels: ready for review

#1339 fix: nav map toast
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/NavMap.prefab
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/NavmapToastView.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/NavMap/Tests/NavmapToastViewShould.cs
Labels: ready for review

#1351 feat: add referrral program
  kernel/packages/shared/referral/index.ts
  kernel/packages/shared/referral/sagas.ts
  kernel/packages/shared/referral/utils.ts
  kernel/packages/shared/session/sagas.ts
Labels: ready for review

#1353 fix: replace trigger with OverlapBox on AvatarModifierArea
  kernel/package-lock.json
  kernel/package.json
  kernel/public/test-scenes/0.103.avatar-modifiers/game.ts
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarModifiers/AvatarModifierArea.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarModifiers/TriggerArea.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarShape.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/PhysicsSyncController/PhysicsSyncController.cs
  unity-client/ProjectSettings/DynamicsManager.asset
Labels: ready for review

#1349 fix: local world blockers
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/SceneController.cs
Labels: ready for review

#1300 feat: clipboard access
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Clipboard.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Clipboard/Clipboard.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Clipboard/Clipboard.asmdef.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Clipboard/Clipboard.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Clipboard/Clipboard.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Clipboard/Handlers.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Clipboard/Handlers/IClipboardHandler.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Clipboard/Handlers/IClipboardHandler.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Clipboard/Handlers/Standalone.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Clipboard/Handlers/Standalone/ClipboardStandalone.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Clipboard/Handlers/Standalone/ClipboardStandalone.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Clipboard/Handlers/Web.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Clipboard/Handlers/Web/ClipboardWebGL.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Clipboard/Handlers/Web/ClipboardWebGL.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Clipboard/Handlers/Web/Plugins.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Clipboard/Handlers/Web/Plugins/ClipboardWebGL.jslib
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Clipboard/Handlers/Web/Plugins/ClipboardWebGL.jslib.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Clipboard/Tests.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Clipboard/Tests/ClipboardHandler_Mock.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Clipboard/Tests/ClipboardHandler_Mock.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Clipboard/Tests/ClipboardTests.asmdef
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Clipboard/Tests/ClipboardTests.asmdef.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Clipboard/Tests/ClipboardTests.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Clipboard/Tests/ClipboardTests.cs.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/Environment.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Helpers/Utils/Promise.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Helpers/Utils/Promise.cs.meta
  unity-client/Assets/Scripts/MainScripts/MainScripts.asmdef
Labels: ready for review

#1355 fix: onboarding performance issues
  kernel/packages/entryPoints/unity.ts
  kernel/packages/unity-interface/dcl.ts
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/HUD/HUDController.cs
  unity-client/Assets/Tutorial/Prefabs/Common/TutorialRobot/Materials/Black_MTL.mat
  unity-client/Assets/Tutorial/Prefabs/Common/TutorialRobot/Materials/Glow_MTL.mat
  unity-client/Assets/Tutorial/Prefabs/Common/TutorialRobot/Materials/Red_MTL.mat
  unity-client/Assets/Tutorial/Prefabs/Common/TutorialRobot/Materials/White_MTL.mat
  unity-client/Assets/Tutorial/Prefabs/Resources/TutorialController.prefab
  unity-client/Assets/Tutorial/Scripts/TutorialController.cs
Labels: ready for review

#1314 fix: asset bundle conversion dependency issues
  unity-client/Assets/Batch/AssetBundleBuilder.cs
  unity-client/Assets/Batch/AssetBundleBuilderUtils.cs
  unity-client/Assets/Batch/AssetBundleMenuItems.cs
  unity-client/Assets/Batch/Tests/ConversionTests.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Helpers/Utils/ContentServerUtils.cs
Labels: ready for review

#1360 chore: remove nft mask message
  kernel/packages/shared/profiles/actions.ts
  kernel/packages/shared/profiles/sagas.ts
  kernel/test/unit/profiles.saga.test.tsx
Labels: ready for review

#1356 fix: basic material + shadow support
  kernel/packages/decentraland-ecs/src/decentraland/Components.ts
  unity-client/Assets/Resources/Materials/BasicShapeMaterial.mat
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Materials/BasicMaterial.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Materials/PBRMaterial.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Materials/Tests/BasicMaterialShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Materials/Tests/BasicMaterialVisualTests.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Materials/Tests/BasicMaterialVisualTests.cs.meta
  unity-client/Assets/Scripts/Tests/TestHelpers.cs
  unity-client/Assets/Shaders/MaterialTransition/LWRP/Unlit.shader
  unity-client/Assets/Shaders/MaterialTransition/LWRP/Unlit.shader.meta
  unity-client/Assets/Shaders/MaterialTransition/LWRP/UnlitInput.hlsl
  unity-client/Assets/Shaders/MaterialTransition/LWRP/UnlitInput.hlsl.meta
  unity-client/TestResources/VisualTests/BaselineImages/BasicMaterialVisualTests_CastShadowFalseShouldWork_0.png
  unity-client/TestResources/VisualTests/BaselineImages/BasicMaterialVisualTests_CastShadowTrueShouldWork_0.png
Labels: ready for review

#1341 chore: Avatar Renderer code cleanup
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarRenderer.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/BodyShapeController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/FacialFeatureController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/Tests/AvatarRendererShould.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Models/AvatarAssets/WearableItem.cs
  unity-client/Assets/Scripts/MainScripts/DCL/ScriptableObject/Variables/BaseDictionary.cs
Labels: merge me!, ready for review

#1369 fix: show logs by default on preview mode
  kernel/packages/config/index.ts
Labels: ready for review

#1370 fix: some perf improvements to avatar modifier area
  unity-client/Assets/Scripts/MainScripts/DCL/Components/Avatar/AvatarModifiers/TriggerArea.cs
Labels: ready for review

#1344 feat: restore decentra libs
  kernel/.gitignore
  kernel/Makefile
  kernel/package-lock.json
  kernel/package.json
  kernel/packages/build-ecs/index.ts
  kernel/packages/build-ecs/package.json
  kernel/packages/build-ecs/tsconfig.json
  kernel/packages/config/contracts.ts
  kernel/packages/decentraland-amd/Makefile
  kernel/packages/decentraland-amd/package-lock.json
  kernel/packages/decentraland-amd/package.json
  kernel/packages/decentraland-amd/src/amd.ts
  kernel/packages/decentraland-amd/tsconfig.json
  kernel/packages/decentraland-ecs/types/tsconfig.json
  kernel/packages/decentraland-ecs/types/tsconfig.strict.json
  kernel/packages/scene-system/sdk/DevToolsAdapter.ts
  kernel/packages/shared/friends/sagas.ts
  kernel/packages/shared/types.ts
  kernel/packages/shared/world/SceneWorker.ts
  kernel/packages/unity-interface/UnityParcelScene.ts
  kernel/public/ecs-scenes/-200,110-relative-layout-ui/game.ts
  kernel/public/ecs-scenes/-200.-1-user-data/game.ts
  kernel/public/ecs-scenes/-200.-30-libraries/game.ts
  kernel/public/ecs-scenes/-200.-30-libraries/node_modules/eth-wrapper/eth-wrapper.ts
  kernel/public/ecs-scenes/-200.-30-libraries/node_modules/eth-wrapper/eth-wrapper/test.ts
  kernel/public/ecs-scenes/-200.-30-libraries/node_modules/eth-wrapper/package.json
  kernel/public/ecs-scenes/-200.-30-libraries/node_modules/eth-wrapper/tsconfig.json
  kernel/public/ecs-scenes/-200.-30-libraries/package.json
  kernel/public/ecs-scenes/-200.-30-libraries/scene.json
  kernel/public/ecs-scenes/-200.-30-libraries/tsconfig.json
  kernel/public/ecs-scenes/-200.1-base-injected-ecs-module/game.ts
  kernel/public/ecs-scenes/-200.237-validate-global-names/printer.ts
  kernel/public/ecs-scenes/-200.4-ethereum-controller/tsconfig.json
  kernel/scripts/_utils.ts
  kernel/scripts/prepareDist.ts
Labels: merge me!

#1327 fix: camera jitter in moving platforms
  unity-client/Assets/Resources/ScriptableObjects/playerIsOnMovingPlatform.asset
  unity-client/Assets/Resources/ScriptableObjects/playerIsOnMovingPlatform.asset.meta
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Camera/CameraController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Camera/CameraStateTPS.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/CharacterController/DCLCharacterController.cs
  unity-client/Assets/Scripts/MainScripts/DCL/Controllers/Scene/ParcelScene.cs
  unity-client/Assets/Scripts/MainScripts/DCL/ScriptableObject/CommonScriptableObjects.cs
Labels: merge me!, ready for review

#1350 fix: wss mode basecatalogue
  README.md
  kernel/package-lock.json
  kernel/packages/shared/profiles/sagas.ts
  kernel/static/default-profile/download_all.js
Labels: ready for review
